/* tslint:disable */
/* eslint-disable */
/**
 * The Plane REST API
 * The Plane REST API  Visit our quick start guide and full API documentation at [developers.plane.so](https://developers.plane.so/api-reference/introduction).
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@plane.so
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  IntakeIssue,
  IntakeIssueCreateRequest,
  PaginatedIntakeIssueResponse,
  PatchedIntakeIssueUpdateRequest,
} from '../models/index';
import {
    IntakeIssueFromJSON,
    IntakeIssueToJSON,
    IntakeIssueCreateRequestFromJSON,
    IntakeIssueCreateRequestToJSON,
    PaginatedIntakeIssueResponseFromJSON,
    PaginatedIntakeIssueResponseToJSON,
    PatchedIntakeIssueUpdateRequestFromJSON,
    PatchedIntakeIssueUpdateRequestToJSON,
} from '../models/index';

export interface CreateIntakeIssueRequest {
    projectId: string;
    slug: string;
    intakeIssueCreateRequest: IntakeIssueCreateRequest;
}

export interface DeleteIntakeIssueRequest {
    issueId: string;
    projectId: string;
    slug: string;
}

export interface GetIntakeIssuesListRequest {
    projectId: string;
    slug: string;
    cursor?: string;
    expand?: string;
    fields?: string;
    perPage?: number;
}

export interface RetrieveIntakeIssueRequest {
    issueId: string;
    projectId: string;
    slug: string;
}

export interface UpdateIntakeIssueRequest {
    issueId: string;
    projectId: string;
    slug: string;
    patchedIntakeIssueUpdateRequest?: PatchedIntakeIssueUpdateRequest;
}

/**
 * 
 */
export class IntakeApi extends runtime.BaseAPI {

    /**
     * Submit a new issue to the project\'s intake queue for review and triage. Automatically creates the issue with default triage state and tracks activity.
     * Create intake issue
     */
    async createIntakeIssueRaw(requestParameters: CreateIntakeIssueRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IntakeIssue>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling createIntakeIssue().'
            );
        }

        if (requestParameters['slug'] == null) {
            throw new runtime.RequiredError(
                'slug',
                'Required parameter "slug" was null or undefined when calling createIntakeIssue().'
            );
        }

        if (requestParameters['intakeIssueCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'intakeIssueCreateRequest',
                'Required parameter "intakeIssueCreateRequest" was null or undefined when calling createIntakeIssue().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuthentication authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2Authentication", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v1/workspaces/{slug}/projects/{project_id}/intake-issues/`.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId']))).replace(`{${"slug"}}`, encodeURIComponent(String(requestParameters['slug']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: IntakeIssueCreateRequestToJSON(requestParameters['intakeIssueCreateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IntakeIssueFromJSON(jsonValue));
    }

    /**
     * Submit a new issue to the project\'s intake queue for review and triage. Automatically creates the issue with default triage state and tracks activity.
     * Create intake issue
     */
    async createIntakeIssue(requestParameters: CreateIntakeIssueRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IntakeIssue> {
        const response = await this.createIntakeIssueRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Permanently remove an intake issue from the triage queue. Also deletes the underlying issue if it hasn\'t been accepted yet.
     * Delete intake issue
     */
    async deleteIntakeIssueRaw(requestParameters: DeleteIntakeIssueRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['issueId'] == null) {
            throw new runtime.RequiredError(
                'issueId',
                'Required parameter "issueId" was null or undefined when calling deleteIntakeIssue().'
            );
        }

        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling deleteIntakeIssue().'
            );
        }

        if (requestParameters['slug'] == null) {
            throw new runtime.RequiredError(
                'slug',
                'Required parameter "slug" was null or undefined when calling deleteIntakeIssue().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuthentication authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2Authentication", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v1/workspaces/{slug}/projects/{project_id}/intake-issues/{issue_id}/`.replace(`{${"issue_id"}}`, encodeURIComponent(String(requestParameters['issueId']))).replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId']))).replace(`{${"slug"}}`, encodeURIComponent(String(requestParameters['slug']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Permanently remove an intake issue from the triage queue. Also deletes the underlying issue if it hasn\'t been accepted yet.
     * Delete intake issue
     */
    async deleteIntakeIssue(requestParameters: DeleteIntakeIssueRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteIntakeIssueRaw(requestParameters, initOverrides);
    }

    /**
     * Retrieve all issues in the project\'s intake queue. Returns paginated results when listing all intake issues.
     * List intake issues
     */
    async getIntakeIssuesListRaw(requestParameters: GetIntakeIssuesListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedIntakeIssueResponse>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling getIntakeIssuesList().'
            );
        }

        if (requestParameters['slug'] == null) {
            throw new runtime.RequiredError(
                'slug',
                'Required parameter "slug" was null or undefined when calling getIntakeIssuesList().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['expand'] != null) {
            queryParameters['expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['fields'] = requestParameters['fields'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuthentication authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2Authentication", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v1/workspaces/{slug}/projects/{project_id}/intake-issues/`.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId']))).replace(`{${"slug"}}`, encodeURIComponent(String(requestParameters['slug']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedIntakeIssueResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve all issues in the project\'s intake queue. Returns paginated results when listing all intake issues.
     * List intake issues
     */
    async getIntakeIssuesList(requestParameters: GetIntakeIssuesListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedIntakeIssueResponse> {
        const response = await this.getIntakeIssuesListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve details of a specific intake issue.
     * Retrieve intake issue
     */
    async retrieveIntakeIssueRaw(requestParameters: RetrieveIntakeIssueRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IntakeIssue>> {
        if (requestParameters['issueId'] == null) {
            throw new runtime.RequiredError(
                'issueId',
                'Required parameter "issueId" was null or undefined when calling retrieveIntakeIssue().'
            );
        }

        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling retrieveIntakeIssue().'
            );
        }

        if (requestParameters['slug'] == null) {
            throw new runtime.RequiredError(
                'slug',
                'Required parameter "slug" was null or undefined when calling retrieveIntakeIssue().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuthentication authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2Authentication", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v1/workspaces/{slug}/projects/{project_id}/intake-issues/{issue_id}/`.replace(`{${"issue_id"}}`, encodeURIComponent(String(requestParameters['issueId']))).replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId']))).replace(`{${"slug"}}`, encodeURIComponent(String(requestParameters['slug']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IntakeIssueFromJSON(jsonValue));
    }

    /**
     * Retrieve details of a specific intake issue.
     * Retrieve intake issue
     */
    async retrieveIntakeIssue(requestParameters: RetrieveIntakeIssueRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IntakeIssue> {
        const response = await this.retrieveIntakeIssueRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Modify an existing intake issue\'s properties or status for triage processing. Supports status changes like accept, reject, or mark as duplicate.
     * Update intake issue
     */
    async updateIntakeIssueRaw(requestParameters: UpdateIntakeIssueRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IntakeIssue>> {
        if (requestParameters['issueId'] == null) {
            throw new runtime.RequiredError(
                'issueId',
                'Required parameter "issueId" was null or undefined when calling updateIntakeIssue().'
            );
        }

        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling updateIntakeIssue().'
            );
        }

        if (requestParameters['slug'] == null) {
            throw new runtime.RequiredError(
                'slug',
                'Required parameter "slug" was null or undefined when calling updateIntakeIssue().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuthentication authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2Authentication", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2Authentication", []);
        }

        const response = await this.request({
            path: `/api/v1/workspaces/{slug}/projects/{project_id}/intake-issues/{issue_id}/`.replace(`{${"issue_id"}}`, encodeURIComponent(String(requestParameters['issueId']))).replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId']))).replace(`{${"slug"}}`, encodeURIComponent(String(requestParameters['slug']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchedIntakeIssueUpdateRequestToJSON(requestParameters['patchedIntakeIssueUpdateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IntakeIssueFromJSON(jsonValue));
    }

    /**
     * Modify an existing intake issue\'s properties or status for triage processing. Supports status changes like accept, reject, or mark as duplicate.
     * Update intake issue
     */
    async updateIntakeIssue(requestParameters: UpdateIntakeIssueRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IntakeIssue> {
        const response = await this.updateIntakeIssueRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
