/* tslint:disable */
/* eslint-disable */
/**
 * The Plane REST API
 * The Plane REST API  Visit our quick start guide and full API documentation at [developers.plane.so](https://developers.plane.so/api-reference/introduction).
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@plane.so
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `-2` - Pending
 * * `-1` - Rejected
 * * `0` - Snoozed
 * * `1` - Accepted
 * * `2` - Duplicate
 * @export
 */
export const IntakeIssueStatusEnum = {
    NUMBER_MINUS_2: -2,
    NUMBER_MINUS_1: -1,
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2
} as const;
export type IntakeIssueStatusEnum = typeof IntakeIssueStatusEnum[keyof typeof IntakeIssueStatusEnum];


export function instanceOfIntakeIssueStatusEnum(value: any): boolean {
    for (const key in IntakeIssueStatusEnum) {
        if (Object.prototype.hasOwnProperty.call(IntakeIssueStatusEnum, key)) {
            if (IntakeIssueStatusEnum[key as keyof typeof IntakeIssueStatusEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function IntakeIssueStatusEnumFromJSON(json: any): IntakeIssueStatusEnum {
    return IntakeIssueStatusEnumFromJSONTyped(json, false);
}

export function IntakeIssueStatusEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): IntakeIssueStatusEnum {
    return json as IntakeIssueStatusEnum;
}

export function IntakeIssueStatusEnumToJSON(value?: IntakeIssueStatusEnum | null): any {
    return value as any;
}

export function IntakeIssueStatusEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): IntakeIssueStatusEnum {
    return value as IntakeIssueStatusEnum;
}

