/* tslint:disable */
/* eslint-disable */
/**
 * The Plane REST API
 * The Plane REST API  Visit our quick start guide and full API documentation at [developers.plane.so](https://developers.plane.so/api-reference/introduction).
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@plane.so
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RetrieveIssueAttachment400Response
 */
export interface RetrieveIssueAttachment400Response {
    /**
     * Error message
     * @type {string}
     * @memberof RetrieveIssueAttachment400Response
     */
    error?: string;
    /**
     * Request status
     * @type {boolean}
     * @memberof RetrieveIssueAttachment400Response
     */
    status?: boolean;
}

/**
 * Check if a given object implements the RetrieveIssueAttachment400Response interface.
 */
export function instanceOfRetrieveIssueAttachment400Response(value: object): value is RetrieveIssueAttachment400Response {
    return true;
}

export function RetrieveIssueAttachment400ResponseFromJSON(json: any): RetrieveIssueAttachment400Response {
    return RetrieveIssueAttachment400ResponseFromJSONTyped(json, false);
}

export function RetrieveIssueAttachment400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetrieveIssueAttachment400Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function RetrieveIssueAttachment400ResponseToJSON(json: any): RetrieveIssueAttachment400Response {
    return RetrieveIssueAttachment400ResponseToJSONTyped(json, false);
}

export function RetrieveIssueAttachment400ResponseToJSONTyped(value?: RetrieveIssueAttachment400Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
        'status': value['status'],
    };
}

