/* tslint:disable */
/* eslint-disable */
/**
 * The Plane REST API
 * The Plane REST API  Visit our quick start guide and full API documentation at [developers.plane.so](https://developers.plane.so/api-reference/introduction).
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@plane.so
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransferCycleIssues200Response
 */
export interface TransferCycleIssues200Response {
    /**
     * Success message
     * @type {string}
     * @memberof TransferCycleIssues200Response
     */
    message?: string;
}

/**
 * Check if a given object implements the TransferCycleIssues200Response interface.
 */
export function instanceOfTransferCycleIssues200Response(value: object): value is TransferCycleIssues200Response {
    return true;
}

export function TransferCycleIssues200ResponseFromJSON(json: any): TransferCycleIssues200Response {
    return TransferCycleIssues200ResponseFromJSONTyped(json, false);
}

export function TransferCycleIssues200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferCycleIssues200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function TransferCycleIssues200ResponseToJSON(json: any): TransferCycleIssues200Response {
    return TransferCycleIssues200ResponseToJSONTyped(json, false);
}

export function TransferCycleIssues200ResponseToJSONTyped(value?: TransferCycleIssues200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

