name: Publish Node SDK to npm

on:
    pull_request:
        branches:
            - main

    push:
        branches:
            - fix-eslint

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install dependencies
              run: pnpm install

            - name: Run lint
              run: pnpm check:lint

            - name: Run format
              run: pnpm check:format

            - name: Run tests
              run: pnpm test
