/* tslint:disable */
/* eslint-disable */
/**
 * Plane API
 * API documentation for my specific app
 *
 * The version of the OpenAPI document: 1.0.0 (1.0.0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TimezoneEnum } from './TimezoneEnum';
import {
    TimezoneEnumFromJSON,
    TimezoneEnumFromJSONTyped,
    TimezoneEnumToJSON,
    TimezoneEnumToJSONTyped,
} from './TimezoneEnum';

/**
 * 
 * @export
 * @interface CycleLite
 */
export interface CycleLite {
    /**
     * 
     * @type {Date}
     * @memberof CycleLite
     */
    archivedAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof CycleLite
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof CycleLite
     */
    createdBy?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof CycleLite
     */
    deletedAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof CycleLite
     */
    description?: string;
    /**
     * 
     * @type {Date}
     * @memberof CycleLite
     */
    endDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof CycleLite
     */
    externalId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CycleLite
     */
    externalSource?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CycleLite
     */
    readonly id: string;
    /**
     * 
     * @type {any}
     * @memberof CycleLite
     */
    logoProps?: any | null;
    /**
     * 
     * @type {string}
     * @memberof CycleLite
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CycleLite
     */
    ownedBy: string;
    /**
     * 
     * @type {any}
     * @memberof CycleLite
     */
    progressSnapshot?: any | null;
    /**
     * 
     * @type {string}
     * @memberof CycleLite
     */
    project: string;
    /**
     * 
     * @type {number}
     * @memberof CycleLite
     */
    sortOrder?: number;
    /**
     * 
     * @type {Date}
     * @memberof CycleLite
     */
    startDate?: Date | null;
    /**
     * 
     * @type {TimezoneEnum}
     * @memberof CycleLite
     */
    timezone?: TimezoneEnum;
    /**
     * 
     * @type {Date}
     * @memberof CycleLite
     */
    readonly updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof CycleLite
     */
    updatedBy?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CycleLite
     */
    version?: number;
    /**
     * 
     * @type {any}
     * @memberof CycleLite
     */
    viewProps?: any | null;
    /**
     * 
     * @type {string}
     * @memberof CycleLite
     */
    workspace: string;
}



/**
 * Check if a given object implements the CycleLite interface.
 */
export function instanceOfCycleLite(value: object): value is CycleLite {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('ownedBy' in value) || value['ownedBy'] === undefined) return false;
    if (!('project' in value) || value['project'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('workspace' in value) || value['workspace'] === undefined) return false;
    return true;
}

export function CycleLiteFromJSON(json: any): CycleLite {
    return CycleLiteFromJSONTyped(json, false);
}

export function CycleLiteFromJSONTyped(json: any, ignoreDiscriminator: boolean): CycleLite {
    if (json == null) {
        return json;
    }
    return {
        
        'archivedAt': json['archived_at'] == null ? undefined : (new Date(json['archived_at'])),
        'createdAt': (new Date(json['created_at'])),
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
        'deletedAt': json['deleted_at'] == null ? undefined : (new Date(json['deleted_at'])),
        'description': json['description'] == null ? undefined : json['description'],
        'endDate': json['end_date'] == null ? undefined : (new Date(json['end_date'])),
        'externalId': json['external_id'] == null ? undefined : json['external_id'],
        'externalSource': json['external_source'] == null ? undefined : json['external_source'],
        'id': json['id'],
        'logoProps': json['logo_props'] == null ? undefined : json['logo_props'],
        'name': json['name'],
        'ownedBy': json['owned_by'],
        'progressSnapshot': json['progress_snapshot'] == null ? undefined : json['progress_snapshot'],
        'project': json['project'],
        'sortOrder': json['sort_order'] == null ? undefined : json['sort_order'],
        'startDate': json['start_date'] == null ? undefined : (new Date(json['start_date'])),
        'timezone': json['timezone'] == null ? undefined : TimezoneEnumFromJSON(json['timezone']),
        'updatedAt': (new Date(json['updated_at'])),
        'updatedBy': json['updated_by'] == null ? undefined : json['updated_by'],
        'version': json['version'] == null ? undefined : json['version'],
        'viewProps': json['view_props'] == null ? undefined : json['view_props'],
        'workspace': json['workspace'],
    };
}

export function CycleLiteToJSON(json: any): CycleLite {
    return CycleLiteToJSONTyped(json, false);
}

export function CycleLiteToJSONTyped(value?: Omit<CycleLite, 'created_at'|'id'|'updated_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'archived_at': value['archivedAt'] == null ? undefined : ((value['archivedAt'] as any).toISOString()),
        'created_by': value['createdBy'],
        'deleted_at': value['deletedAt'] == null ? undefined : ((value['deletedAt'] as any).toISOString()),
        'description': value['description'],
        'end_date': value['endDate'] == null ? undefined : ((value['endDate'] as any).toISOString()),
        'external_id': value['externalId'],
        'external_source': value['externalSource'],
        'logo_props': value['logoProps'],
        'name': value['name'],
        'owned_by': value['ownedBy'],
        'progress_snapshot': value['progressSnapshot'],
        'project': value['project'],
        'sort_order': value['sortOrder'],
        'start_date': value['startDate'] == null ? undefined : ((value['startDate'] as any).toISOString()),
        'timezone': TimezoneEnumToJSON(value['timezone']),
        'updated_by': value['updatedBy'],
        'version': value['version'],
        'view_props': value['viewProps'],
        'workspace': value['workspace'],
    };
}

