/* tslint:disable */
/* eslint-disable */
/**
 * Plane API
 * API documentation for my specific app
 *
 * The version of the OpenAPI document: 1.0.0 (1.0.0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CycleIssue
 */
export interface CycleIssue {
    /**
     * 
     * @type {Date}
     * @memberof CycleIssue
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof CycleIssue
     */
    createdBy?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CycleIssue
     */
    readonly cycle: string;
    /**
     * 
     * @type {Date}
     * @memberof CycleIssue
     */
    deletedAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof CycleIssue
     */
    readonly id: string;
    /**
     * 
     * @type {string}
     * @memberof CycleIssue
     */
    issue: string;
    /**
     * 
     * @type {string}
     * @memberof CycleIssue
     */
    readonly project: string;
    /**
     * 
     * @type {number}
     * @memberof CycleIssue
     */
    readonly subIssuesCount: number;
    /**
     * 
     * @type {Date}
     * @memberof CycleIssue
     */
    readonly updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof CycleIssue
     */
    updatedBy?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CycleIssue
     */
    readonly workspace: string;
}

/**
 * Check if a given object implements the CycleIssue interface.
 */
export function instanceOfCycleIssue(value: object): value is CycleIssue {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('cycle' in value) || value['cycle'] === undefined) return false;
    if (!('deletedAt' in value) || value['deletedAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('issue' in value) || value['issue'] === undefined) return false;
    if (!('project' in value) || value['project'] === undefined) return false;
    if (!('subIssuesCount' in value) || value['subIssuesCount'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('workspace' in value) || value['workspace'] === undefined) return false;
    return true;
}

export function CycleIssueFromJSON(json: any): CycleIssue {
    return CycleIssueFromJSONTyped(json, false);
}

export function CycleIssueFromJSONTyped(json: any, ignoreDiscriminator: boolean): CycleIssue {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': (new Date(json['created_at'])),
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
        'cycle': json['cycle'],
        'deletedAt': (json['deleted_at'] == null ? null : new Date(json['deleted_at'])),
        'id': json['id'],
        'issue': json['issue'],
        'project': json['project'],
        'subIssuesCount': json['sub_issues_count'],
        'updatedAt': (new Date(json['updated_at'])),
        'updatedBy': json['updated_by'] == null ? undefined : json['updated_by'],
        'workspace': json['workspace'],
    };
}

export function CycleIssueToJSON(json: any): CycleIssue {
    return CycleIssueToJSONTyped(json, false);
}

export function CycleIssueToJSONTyped(value?: Omit<CycleIssue, 'created_at'|'cycle'|'id'|'project'|'sub_issues_count'|'updated_at'|'workspace'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_by': value['createdBy'],
        'deleted_at': (value['deletedAt'] == null ? null : (value['deletedAt'] as any).toISOString()),
        'issue': value['issue'],
        'updated_by': value['updatedBy'],
    };
}

