/* tslint:disable */
/* eslint-disable */
/**
 * Plane API
 * API documentation for my specific app
 *
 * The version of the OpenAPI document: 1.0.0 (1.0.0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IssueTypeAPI
 */
export interface IssueTypeAPI {
    /**
     * 
     * @type {Date}
     * @memberof IssueTypeAPI
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof IssueTypeAPI
     */
    readonly createdBy: string | null;
    /**
     * 
     * @type {Date}
     * @memberof IssueTypeAPI
     */
    readonly deletedAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof IssueTypeAPI
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof IssueTypeAPI
     */
    externalId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IssueTypeAPI
     */
    externalSource?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IssueTypeAPI
     */
    readonly id: string;
    /**
     * 
     * @type {boolean}
     * @memberof IssueTypeAPI
     */
    isActive?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof IssueTypeAPI
     */
    readonly isDefault: boolean;
    /**
     * 
     * @type {number}
     * @memberof IssueTypeAPI
     */
    readonly level: number;
    /**
     * 
     * @type {any}
     * @memberof IssueTypeAPI
     */
    readonly logoProps: any | null;
    /**
     * 
     * @type {string}
     * @memberof IssueTypeAPI
     */
    name: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof IssueTypeAPI
     */
    projectIds?: Array<string>;
    /**
     * 
     * @type {Date}
     * @memberof IssueTypeAPI
     */
    readonly updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof IssueTypeAPI
     */
    readonly updatedBy: string | null;
    /**
     * 
     * @type {string}
     * @memberof IssueTypeAPI
     */
    readonly workspace: string;
}

/**
 * Check if a given object implements the IssueTypeAPI interface.
 */
export function instanceOfIssueTypeAPI(value: object): value is IssueTypeAPI {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('deletedAt' in value) || value['deletedAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('isDefault' in value) || value['isDefault'] === undefined) return false;
    if (!('level' in value) || value['level'] === undefined) return false;
    if (!('logoProps' in value) || value['logoProps'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('updatedBy' in value) || value['updatedBy'] === undefined) return false;
    if (!('workspace' in value) || value['workspace'] === undefined) return false;
    return true;
}

export function IssueTypeAPIFromJSON(json: any): IssueTypeAPI {
    return IssueTypeAPIFromJSONTyped(json, false);
}

export function IssueTypeAPIFromJSONTyped(json: any, ignoreDiscriminator: boolean): IssueTypeAPI {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': (new Date(json['created_at'])),
        'createdBy': json['created_by'],
        'deletedAt': (json['deleted_at'] == null ? null : new Date(json['deleted_at'])),
        'description': json['description'] == null ? undefined : json['description'],
        'externalId': json['external_id'] == null ? undefined : json['external_id'],
        'externalSource': json['external_source'] == null ? undefined : json['external_source'],
        'id': json['id'],
        'isActive': json['is_active'] == null ? undefined : json['is_active'],
        'isDefault': json['is_default'],
        'level': json['level'],
        'logoProps': json['logo_props'],
        'name': json['name'],
        'projectIds': json['project_ids'] == null ? undefined : json['project_ids'],
        'updatedAt': (new Date(json['updated_at'])),
        'updatedBy': json['updated_by'],
        'workspace': json['workspace'],
    };
}

export function IssueTypeAPIToJSON(json: any): IssueTypeAPI {
    return IssueTypeAPIToJSONTyped(json, false);
}

export function IssueTypeAPIToJSONTyped(value?: Omit<IssueTypeAPI, 'created_at'|'created_by'|'deleted_at'|'id'|'is_default'|'level'|'logo_props'|'updated_at'|'updated_by'|'workspace'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'external_id': value['externalId'],
        'external_source': value['externalSource'],
        'is_active': value['isActive'],
        'name': value['name'],
        'project_ids': value['projectIds'],
    };
}

