/* tslint:disable */
/* eslint-disable */
/**
 * Plane API
 * API documentation for my specific app
 *
 * The version of the OpenAPI document: 1.0.0 (1.0.0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type IssueAttachmentEntityType
 * 
 * @export
 */
export type IssueAttachmentEntityType = BlankEnum | EntityTypeEnum;

export function IssueAttachmentEntityTypeFromJSON(json: any): IssueAttachmentEntityType {
    return IssueAttachmentEntityTypeFromJSONTyped(json, false);
}

export function IssueAttachmentEntityTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): IssueAttachmentEntityType {
    if (json == null) {
        return json;
    }

    return {} as any;
}

export function IssueAttachmentEntityTypeToJSON(json: any): any {
    return IssueAttachmentEntityTypeToJSONTyped(json, false);
}

export function IssueAttachmentEntityTypeToJSONTyped(value?: IssueAttachmentEntityType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {};
}

