/* tslint:disable */
/* eslint-disable */
/**
 * Plane API
 * API documentation for my specific app
 *
 * The version of the OpenAPI document: 1.0.0 (1.0.0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IssuePropertyOptionAPI
 */
export interface IssuePropertyOptionAPI {
    /**
     * 
     * @type {Date}
     * @memberof IssuePropertyOptionAPI
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof IssuePropertyOptionAPI
     */
    readonly createdBy: string | null;
    /**
     * 
     * @type {Date}
     * @memberof IssuePropertyOptionAPI
     */
    readonly deletedAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof IssuePropertyOptionAPI
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof IssuePropertyOptionAPI
     */
    externalId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IssuePropertyOptionAPI
     */
    externalSource?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IssuePropertyOptionAPI
     */
    readonly id: string;
    /**
     * 
     * @type {boolean}
     * @memberof IssuePropertyOptionAPI
     */
    isActive?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof IssuePropertyOptionAPI
     */
    isDefault?: boolean;
    /**
     * 
     * @type {any}
     * @memberof IssuePropertyOptionAPI
     */
    readonly logoProps: any | null;
    /**
     * 
     * @type {string}
     * @memberof IssuePropertyOptionAPI
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof IssuePropertyOptionAPI
     */
    parent?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IssuePropertyOptionAPI
     */
    readonly project: string | null;
    /**
     * 
     * @type {string}
     * @memberof IssuePropertyOptionAPI
     */
    readonly property: string;
    /**
     * 
     * @type {number}
     * @memberof IssuePropertyOptionAPI
     */
    readonly sortOrder: number;
    /**
     * 
     * @type {Date}
     * @memberof IssuePropertyOptionAPI
     */
    readonly updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof IssuePropertyOptionAPI
     */
    readonly updatedBy: string | null;
    /**
     * 
     * @type {string}
     * @memberof IssuePropertyOptionAPI
     */
    readonly workspace: string;
}

/**
 * Check if a given object implements the IssuePropertyOptionAPI interface.
 */
export function instanceOfIssuePropertyOptionAPI(value: object): value is IssuePropertyOptionAPI {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('deletedAt' in value) || value['deletedAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('logoProps' in value) || value['logoProps'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('project' in value) || value['project'] === undefined) return false;
    if (!('property' in value) || value['property'] === undefined) return false;
    if (!('sortOrder' in value) || value['sortOrder'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('updatedBy' in value) || value['updatedBy'] === undefined) return false;
    if (!('workspace' in value) || value['workspace'] === undefined) return false;
    return true;
}

export function IssuePropertyOptionAPIFromJSON(json: any): IssuePropertyOptionAPI {
    return IssuePropertyOptionAPIFromJSONTyped(json, false);
}

export function IssuePropertyOptionAPIFromJSONTyped(json: any, ignoreDiscriminator: boolean): IssuePropertyOptionAPI {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': (new Date(json['created_at'])),
        'createdBy': json['created_by'],
        'deletedAt': (json['deleted_at'] == null ? null : new Date(json['deleted_at'])),
        'description': json['description'] == null ? undefined : json['description'],
        'externalId': json['external_id'] == null ? undefined : json['external_id'],
        'externalSource': json['external_source'] == null ? undefined : json['external_source'],
        'id': json['id'],
        'isActive': json['is_active'] == null ? undefined : json['is_active'],
        'isDefault': json['is_default'] == null ? undefined : json['is_default'],
        'logoProps': json['logo_props'],
        'name': json['name'],
        'parent': json['parent'] == null ? undefined : json['parent'],
        'project': json['project'],
        'property': json['property'],
        'sortOrder': json['sort_order'],
        'updatedAt': (new Date(json['updated_at'])),
        'updatedBy': json['updated_by'],
        'workspace': json['workspace'],
    };
}

export function IssuePropertyOptionAPIToJSON(json: any): IssuePropertyOptionAPI {
    return IssuePropertyOptionAPIToJSONTyped(json, false);
}

export function IssuePropertyOptionAPIToJSONTyped(value?: Omit<IssuePropertyOptionAPI, 'created_at'|'created_by'|'deleted_at'|'id'|'logo_props'|'project'|'property'|'sort_order'|'updated_at'|'updated_by'|'workspace'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'external_id': value['externalId'],
        'external_source': value['externalSource'],
        'is_active': value['isActive'],
        'is_default': value['isDefault'],
        'name': value['name'],
        'parent': value['parent'],
    };
}

