/* tslint:disable */
/* eslint-disable */
/**
 * Plane API
 * API documentation for my specific app
 *
 * The version of the OpenAPI document: 1.0.0 (1.0.0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IssueAttachmentEntityType } from './IssueAttachmentEntityType';
import {
    IssueAttachmentEntityTypeFromJSON,
    IssueAttachmentEntityTypeFromJSONTyped,
    IssueAttachmentEntityTypeToJSON,
    IssueAttachmentEntityTypeToJSONTyped,
} from './IssueAttachmentEntityType';

/**
 * 
 * @export
 * @interface IssueAttachment
 */
export interface IssueAttachment {
    /**
     * 
     * @type {string}
     * @memberof IssueAttachment
     */
    asset: string;
    /**
     * 
     * @type {any}
     * @memberof IssueAttachment
     */
    attributes?: any | null;
    /**
     * 
     * @type {string}
     * @memberof IssueAttachment
     */
    comment?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof IssueAttachment
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof IssueAttachment
     */
    createdBy?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof IssueAttachment
     */
    deletedAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof IssueAttachment
     */
    draftIssue?: string | null;
    /**
     * 
     * @type {IssueAttachmentEntityType}
     * @memberof IssueAttachment
     */
    entityType?: IssueAttachmentEntityType | null;
    /**
     * 
     * @type {string}
     * @memberof IssueAttachment
     */
    externalId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IssueAttachment
     */
    externalSource?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IssueAttachment
     */
    readonly id: string;
    /**
     * 
     * @type {boolean}
     * @memberof IssueAttachment
     */
    isArchived?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof IssueAttachment
     */
    isDeleted?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof IssueAttachment
     */
    isUploaded?: boolean;
    /**
     * 
     * @type {string}
     * @memberof IssueAttachment
     */
    readonly issue: string | null;
    /**
     * 
     * @type {string}
     * @memberof IssueAttachment
     */
    page?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IssueAttachment
     */
    readonly project: string | null;
    /**
     * 
     * @type {number}
     * @memberof IssueAttachment
     */
    size?: number;
    /**
     * 
     * @type {any}
     * @memberof IssueAttachment
     */
    storageMetadata?: any | null;
    /**
     * 
     * @type {Date}
     * @memberof IssueAttachment
     */
    readonly updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof IssueAttachment
     */
    readonly updatedBy: string | null;
    /**
     * 
     * @type {string}
     * @memberof IssueAttachment
     */
    user?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IssueAttachment
     */
    readonly workspace: string | null;
}

/**
 * Check if a given object implements the IssueAttachment interface.
 */
export function instanceOfIssueAttachment(value: object): value is IssueAttachment {
    if (!('asset' in value) || value['asset'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('issue' in value) || value['issue'] === undefined) return false;
    if (!('project' in value) || value['project'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('updatedBy' in value) || value['updatedBy'] === undefined) return false;
    if (!('workspace' in value) || value['workspace'] === undefined) return false;
    return true;
}

export function IssueAttachmentFromJSON(json: any): IssueAttachment {
    return IssueAttachmentFromJSONTyped(json, false);
}

export function IssueAttachmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): IssueAttachment {
    if (json == null) {
        return json;
    }
    return {
        
        'asset': json['asset'],
        'attributes': json['attributes'] == null ? undefined : json['attributes'],
        'comment': json['comment'] == null ? undefined : json['comment'],
        'createdAt': (new Date(json['created_at'])),
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
        'deletedAt': json['deleted_at'] == null ? undefined : (new Date(json['deleted_at'])),
        'draftIssue': json['draft_issue'] == null ? undefined : json['draft_issue'],
        'entityType': json['entity_type'] == null ? undefined : IssueAttachmentEntityTypeFromJSON(json['entity_type']),
        'externalId': json['external_id'] == null ? undefined : json['external_id'],
        'externalSource': json['external_source'] == null ? undefined : json['external_source'],
        'id': json['id'],
        'isArchived': json['is_archived'] == null ? undefined : json['is_archived'],
        'isDeleted': json['is_deleted'] == null ? undefined : json['is_deleted'],
        'isUploaded': json['is_uploaded'] == null ? undefined : json['is_uploaded'],
        'issue': json['issue'],
        'page': json['page'] == null ? undefined : json['page'],
        'project': json['project'],
        'size': json['size'] == null ? undefined : json['size'],
        'storageMetadata': json['storage_metadata'] == null ? undefined : json['storage_metadata'],
        'updatedAt': (new Date(json['updated_at'])),
        'updatedBy': json['updated_by'],
        'user': json['user'] == null ? undefined : json['user'],
        'workspace': json['workspace'],
    };
}

export function IssueAttachmentToJSON(json: any): IssueAttachment {
    return IssueAttachmentToJSONTyped(json, false);
}

export function IssueAttachmentToJSONTyped(value?: Omit<IssueAttachment, 'created_at'|'id'|'issue'|'project'|'updated_at'|'updated_by'|'workspace'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'asset': value['asset'],
        'attributes': value['attributes'],
        'comment': value['comment'],
        'created_by': value['createdBy'],
        'deleted_at': value['deletedAt'] == null ? undefined : ((value['deletedAt'] as any).toISOString()),
        'draft_issue': value['draftIssue'],
        'entity_type': IssueAttachmentEntityTypeToJSON(value['entityType']),
        'external_id': value['externalId'],
        'external_source': value['externalSource'],
        'is_archived': value['isArchived'],
        'is_deleted': value['isDeleted'],
        'is_uploaded': value['isUploaded'],
        'page': value['page'],
        'size': value['size'],
        'storage_metadata': value['storageMetadata'],
        'user': value['user'],
    };
}

