/* tslint:disable */
/* eslint-disable */
/**
 * Plane API
 * API documentation for my specific app
 *
 * The version of the OpenAPI document: 1.0.0 (1.0.0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type IssuePropertyAPIRelationType
 * 
 * @export
 */
export type IssuePropertyAPIRelationType = BlankEnum | RelationTypeEnum;

export function IssuePropertyAPIRelationTypeFromJSON(json: any): IssuePropertyAPIRelationType {
    return IssuePropertyAPIRelationTypeFromJSONTyped(json, false);
}

export function IssuePropertyAPIRelationTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): IssuePropertyAPIRelationType {
    if (json == null) {
        return json;
    }

    return {} as any;
}

export function IssuePropertyAPIRelationTypeToJSON(json: any): any {
    return IssuePropertyAPIRelationTypeToJSONTyped(json, false);
}

export function IssuePropertyAPIRelationTypeToJSONTyped(value?: IssuePropertyAPIRelationType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {};
}

