/* tslint:disable */
/* eslint-disable */
/**
 * Plane API
 * API documentation for my specific app
 *
 * The version of the OpenAPI document: 1.0.0 (1.0.0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PriorityEnum } from './PriorityEnum';
import {
    PriorityEnumFromJSON,
    PriorityEnumFromJSONTyped,
    PriorityEnumToJSON,
    PriorityEnumToJSONTyped,
} from './PriorityEnum';
import type { StateLite } from './StateLite';
import {
    StateLiteFromJSON,
    StateLiteFromJSONTyped,
    StateLiteToJSON,
    StateLiteToJSONTyped,
} from './StateLite';
import type { LabelLite } from './LabelLite';
import {
    LabelLiteFromJSON,
    LabelLiteFromJSONTyped,
    LabelLiteToJSON,
    LabelLiteToJSONTyped,
} from './LabelLite';
import type { CycleLite } from './CycleLite';
import {
    CycleLiteFromJSON,
    CycleLiteFromJSONTyped,
    CycleLiteToJSON,
    CycleLiteToJSONTyped,
} from './CycleLite';
import type { ModuleLite } from './ModuleLite';
import {
    ModuleLiteFromJSON,
    ModuleLiteFromJSONTyped,
    ModuleLiteToJSON,
    ModuleLiteToJSONTyped,
} from './ModuleLite';
import type { UserLite } from './UserLite';
import {
    UserLiteFromJSON,
    UserLiteFromJSONTyped,
    UserLiteToJSON,
    UserLiteToJSONTyped,
} from './UserLite';

/**
 * 
 * @export
 * @interface IssueExpand
 */
export interface IssueExpand {
    /**
     * 
     * @type {Date}
     * @memberof IssueExpand
     */
    archivedAt?: Date | null;
    /**
     * 
     * @type {Array<UserLite>}
     * @memberof IssueExpand
     */
    readonly assignees: Array<UserLite>;
    /**
     * 
     * @type {Date}
     * @memberof IssueExpand
     */
    completedAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof IssueExpand
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof IssueExpand
     */
    readonly createdBy: string | null;
    /**
     * 
     * @type {CycleLite}
     * @memberof IssueExpand
     */
    readonly cycle: CycleLite;
    /**
     * 
     * @type {Date}
     * @memberof IssueExpand
     */
    deletedAt?: Date | null;
    /**
     * 
     * @type {any}
     * @memberof IssueExpand
     */
    description?: any | null;
    /**
     * 
     * @type {string}
     * @memberof IssueExpand
     */
    readonly descriptionBinary: string | null;
    /**
     * 
     * @type {string}
     * @memberof IssueExpand
     */
    descriptionHtml?: string;
    /**
     * 
     * @type {string}
     * @memberof IssueExpand
     */
    descriptionStripped?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IssueExpand
     */
    estimatePoint?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IssueExpand
     */
    externalId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IssueExpand
     */
    externalSource?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IssueExpand
     */
    readonly id: string;
    /**
     * 
     * @type {boolean}
     * @memberof IssueExpand
     */
    isDraft?: boolean;
    /**
     * 
     * @type {Array<LabelLite>}
     * @memberof IssueExpand
     */
    readonly labels: Array<LabelLite>;
    /**
     * 
     * @type {ModuleLite}
     * @memberof IssueExpand
     */
    readonly module: ModuleLite;
    /**
     * 
     * @type {string}
     * @memberof IssueExpand
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof IssueExpand
     */
    parent?: string | null;
    /**
     * 
     * @type {number}
     * @memberof IssueExpand
     */
    point?: number | null;
    /**
     * 
     * @type {PriorityEnum}
     * @memberof IssueExpand
     */
    priority?: PriorityEnum;
    /**
     * 
     * @type {string}
     * @memberof IssueExpand
     */
    readonly project: string;
    /**
     * 
     * @type {number}
     * @memberof IssueExpand
     */
    sequenceId?: number;
    /**
     * 
     * @type {number}
     * @memberof IssueExpand
     */
    sortOrder?: number;
    /**
     * 
     * @type {Date}
     * @memberof IssueExpand
     */
    startDate?: Date | null;
    /**
     * 
     * @type {StateLite}
     * @memberof IssueExpand
     */
    readonly state: StateLite;
    /**
     * 
     * @type {Date}
     * @memberof IssueExpand
     */
    targetDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof IssueExpand
     */
    type?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof IssueExpand
     */
    readonly updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof IssueExpand
     */
    readonly updatedBy: string | null;
    /**
     * 
     * @type {string}
     * @memberof IssueExpand
     */
    readonly workspace: string;
}



/**
 * Check if a given object implements the IssueExpand interface.
 */
export function instanceOfIssueExpand(value: object): value is IssueExpand {
    if (!('assignees' in value) || value['assignees'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('cycle' in value) || value['cycle'] === undefined) return false;
    if (!('descriptionBinary' in value) || value['descriptionBinary'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('labels' in value) || value['labels'] === undefined) return false;
    if (!('module' in value) || value['module'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('project' in value) || value['project'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('updatedBy' in value) || value['updatedBy'] === undefined) return false;
    if (!('workspace' in value) || value['workspace'] === undefined) return false;
    return true;
}

export function IssueExpandFromJSON(json: any): IssueExpand {
    return IssueExpandFromJSONTyped(json, false);
}

export function IssueExpandFromJSONTyped(json: any, ignoreDiscriminator: boolean): IssueExpand {
    if (json == null) {
        return json;
    }
    return {
        
        'archivedAt': json['archived_at'] == null ? undefined : (new Date(json['archived_at'])),
        'assignees': ((json['assignees'] as Array<any>).map(UserLiteFromJSON)),
        'completedAt': json['completed_at'] == null ? undefined : (new Date(json['completed_at'])),
        'createdAt': (new Date(json['created_at'])),
        'createdBy': json['created_by'],
        'cycle': CycleLiteFromJSON(json['cycle']),
        'deletedAt': json['deleted_at'] == null ? undefined : (new Date(json['deleted_at'])),
        'description': json['description'] == null ? undefined : json['description'],
        'descriptionBinary': json['description_binary'],
        'descriptionHtml': json['description_html'] == null ? undefined : json['description_html'],
        'descriptionStripped': json['description_stripped'] == null ? undefined : json['description_stripped'],
        'estimatePoint': json['estimate_point'] == null ? undefined : json['estimate_point'],
        'externalId': json['external_id'] == null ? undefined : json['external_id'],
        'externalSource': json['external_source'] == null ? undefined : json['external_source'],
        'id': json['id'],
        'isDraft': json['is_draft'] == null ? undefined : json['is_draft'],
        'labels': ((json['labels'] as Array<any>).map(LabelLiteFromJSON)),
        'module': ModuleLiteFromJSON(json['module']),
        'name': json['name'],
        'parent': json['parent'] == null ? undefined : json['parent'],
        'point': json['point'] == null ? undefined : json['point'],
        'priority': json['priority'] == null ? undefined : PriorityEnumFromJSON(json['priority']),
        'project': json['project'],
        'sequenceId': json['sequence_id'] == null ? undefined : json['sequence_id'],
        'sortOrder': json['sort_order'] == null ? undefined : json['sort_order'],
        'startDate': json['start_date'] == null ? undefined : (new Date(json['start_date'])),
        'state': StateLiteFromJSON(json['state']),
        'targetDate': json['target_date'] == null ? undefined : (new Date(json['target_date'])),
        'type': json['type'] == null ? undefined : json['type'],
        'updatedAt': (new Date(json['updated_at'])),
        'updatedBy': json['updated_by'],
        'workspace': json['workspace'],
    };
}

export function IssueExpandToJSON(json: any): IssueExpand {
    return IssueExpandToJSONTyped(json, false);
}

export function IssueExpandToJSONTyped(value?: Omit<IssueExpand, 'assignees'|'created_at'|'created_by'|'cycle'|'description_binary'|'id'|'labels'|'module'|'project'|'state'|'updated_at'|'updated_by'|'workspace'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'archived_at': value['archivedAt'] == null ? undefined : ((value['archivedAt'] as any).toISOString().substring(0,10)),
        'completed_at': value['completedAt'] == null ? undefined : ((value['completedAt'] as any).toISOString()),
        'deleted_at': value['deletedAt'] == null ? undefined : ((value['deletedAt'] as any).toISOString()),
        'description': value['description'],
        'description_html': value['descriptionHtml'],
        'description_stripped': value['descriptionStripped'],
        'estimate_point': value['estimatePoint'],
        'external_id': value['externalId'],
        'external_source': value['externalSource'],
        'is_draft': value['isDraft'],
        'name': value['name'],
        'parent': value['parent'],
        'point': value['point'],
        'priority': PriorityEnumToJSON(value['priority']),
        'sequence_id': value['sequenceId'],
        'sort_order': value['sortOrder'],
        'start_date': value['startDate'] == null ? undefined : ((value['startDate'] as any).toISOString().substring(0,10)),
        'target_date': value['targetDate'] == null ? undefined : ((value['targetDate'] as any).toISOString().substring(0,10)),
        'type': value['type'],
    };
}

