/* tslint:disable */
/* eslint-disable */
/**
 * Plane API
 * API documentation for my specific app
 *
 * The version of the OpenAPI document: 1.0.0 (1.0.0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IssuePropertyValueAPI
 */
export interface IssuePropertyValueAPI {
    /**
     * 
     * @type {Date}
     * @memberof IssuePropertyValueAPI
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof IssuePropertyValueAPI
     */
    readonly createdBy: string | null;
    /**
     * 
     * @type {Date}
     * @memberof IssuePropertyValueAPI
     */
    readonly deletedAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof IssuePropertyValueAPI
     */
    externalId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IssuePropertyValueAPI
     */
    externalSource?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IssuePropertyValueAPI
     */
    readonly id: string;
    /**
     * 
     * @type {string}
     * @memberof IssuePropertyValueAPI
     */
    issue: string;
    /**
     * 
     * @type {string}
     * @memberof IssuePropertyValueAPI
     */
    readonly project: string | null;
    /**
     * 
     * @type {string}
     * @memberof IssuePropertyValueAPI
     */
    property: string;
    /**
     * 
     * @type {Date}
     * @memberof IssuePropertyValueAPI
     */
    readonly updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof IssuePropertyValueAPI
     */
    readonly updatedBy: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof IssuePropertyValueAPI
     */
    valueBoolean?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof IssuePropertyValueAPI
     */
    valueDatetime?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof IssuePropertyValueAPI
     */
    valueDecimal?: number;
    /**
     * 
     * @type {string}
     * @memberof IssuePropertyValueAPI
     */
    valueOption?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IssuePropertyValueAPI
     */
    valueText?: string;
    /**
     * 
     * @type {string}
     * @memberof IssuePropertyValueAPI
     */
    valueUuid?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IssuePropertyValueAPI
     */
    readonly workspace: string;
}

/**
 * Check if a given object implements the IssuePropertyValueAPI interface.
 */
export function instanceOfIssuePropertyValueAPI(value: object): value is IssuePropertyValueAPI {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('deletedAt' in value) || value['deletedAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('issue' in value) || value['issue'] === undefined) return false;
    if (!('project' in value) || value['project'] === undefined) return false;
    if (!('property' in value) || value['property'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('updatedBy' in value) || value['updatedBy'] === undefined) return false;
    if (!('workspace' in value) || value['workspace'] === undefined) return false;
    return true;
}

export function IssuePropertyValueAPIFromJSON(json: any): IssuePropertyValueAPI {
    return IssuePropertyValueAPIFromJSONTyped(json, false);
}

export function IssuePropertyValueAPIFromJSONTyped(json: any, ignoreDiscriminator: boolean): IssuePropertyValueAPI {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': (new Date(json['created_at'])),
        'createdBy': json['created_by'],
        'deletedAt': (json['deleted_at'] == null ? null : new Date(json['deleted_at'])),
        'externalId': json['external_id'] == null ? undefined : json['external_id'],
        'externalSource': json['external_source'] == null ? undefined : json['external_source'],
        'id': json['id'],
        'issue': json['issue'],
        'project': json['project'],
        'property': json['property'],
        'updatedAt': (new Date(json['updated_at'])),
        'updatedBy': json['updated_by'],
        'valueBoolean': json['value_boolean'] == null ? undefined : json['value_boolean'],
        'valueDatetime': json['value_datetime'] == null ? undefined : (new Date(json['value_datetime'])),
        'valueDecimal': json['value_decimal'] == null ? undefined : json['value_decimal'],
        'valueOption': json['value_option'] == null ? undefined : json['value_option'],
        'valueText': json['value_text'] == null ? undefined : json['value_text'],
        'valueUuid': json['value_uuid'] == null ? undefined : json['value_uuid'],
        'workspace': json['workspace'],
    };
}

export function IssuePropertyValueAPIToJSON(json: any): IssuePropertyValueAPI {
    return IssuePropertyValueAPIToJSONTyped(json, false);
}

export function IssuePropertyValueAPIToJSONTyped(value?: Omit<IssuePropertyValueAPI, 'created_at'|'created_by'|'deleted_at'|'id'|'project'|'updated_at'|'updated_by'|'workspace'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'external_id': value['externalId'],
        'external_source': value['externalSource'],
        'issue': value['issue'],
        'property': value['property'],
        'value_boolean': value['valueBoolean'],
        'value_datetime': value['valueDatetime'] == null ? undefined : ((value['valueDatetime'] as any).toISOString()),
        'value_decimal': value['valueDecimal'],
        'value_option': value['valueOption'],
        'value_text': value['valueText'],
        'value_uuid': value['valueUuid'],
    };
}

