/* tslint:disable */
/* eslint-disable */
/**
 * Plane API
 * API documentation for my specific app
 *
 * The version of the OpenAPI document: 1.0.0 (1.0.0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LabelLite
 */
export interface LabelLite {
    /**
     * 
     * @type {string}
     * @memberof LabelLite
     */
    color?: string;
    /**
     * 
     * @type {string}
     * @memberof LabelLite
     */
    readonly id: string;
    /**
     * 
     * @type {string}
     * @memberof LabelLite
     */
    name: string;
}

/**
 * Check if a given object implements the LabelLite interface.
 */
export function instanceOfLabelLite(value: object): value is LabelLite {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function LabelLiteFromJSON(json: any): LabelLite {
    return LabelLiteFromJSONTyped(json, false);
}

export function LabelLiteFromJSONTyped(json: any, ignoreDiscriminator: boolean): LabelLite {
    if (json == null) {
        return json;
    }
    return {
        
        'color': json['color'] == null ? undefined : json['color'],
        'id': json['id'],
        'name': json['name'],
    };
}

export function LabelLiteToJSON(json: any): LabelLite {
    return LabelLiteToJSONTyped(json, false);
}

export function LabelLiteToJSONTyped(value?: Omit<LabelLite, 'id'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'color': value['color'],
        'name': value['name'],
    };
}

