/* tslint:disable */
/* eslint-disable */
/**
 * Plane API
 * API documentation for my specific app
 *
 * The version of the OpenAPI document: 1.0.0 (1.0.0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Label
 */
export interface Label {
    /**
     * 
     * @type {string}
     * @memberof Label
     */
    color?: string;
    /**
     * 
     * @type {Date}
     * @memberof Label
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof Label
     */
    readonly createdBy: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Label
     */
    readonly deletedAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof Label
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof Label
     */
    externalId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Label
     */
    externalSource?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Label
     */
    readonly id: string;
    /**
     * 
     * @type {string}
     * @memberof Label
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Label
     */
    parent?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Label
     */
    readonly project: string;
    /**
     * 
     * @type {number}
     * @memberof Label
     */
    sortOrder?: number;
    /**
     * 
     * @type {Date}
     * @memberof Label
     */
    readonly updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof Label
     */
    readonly updatedBy: string | null;
    /**
     * 
     * @type {string}
     * @memberof Label
     */
    readonly workspace: string;
}

/**
 * Check if a given object implements the Label interface.
 */
export function instanceOfLabel(value: object): value is Label {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('deletedAt' in value) || value['deletedAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('project' in value) || value['project'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('updatedBy' in value) || value['updatedBy'] === undefined) return false;
    if (!('workspace' in value) || value['workspace'] === undefined) return false;
    return true;
}

export function LabelFromJSON(json: any): Label {
    return LabelFromJSONTyped(json, false);
}

export function LabelFromJSONTyped(json: any, ignoreDiscriminator: boolean): Label {
    if (json == null) {
        return json;
    }
    return {
        
        'color': json['color'] == null ? undefined : json['color'],
        'createdAt': (new Date(json['created_at'])),
        'createdBy': json['created_by'],
        'deletedAt': (json['deleted_at'] == null ? null : new Date(json['deleted_at'])),
        'description': json['description'] == null ? undefined : json['description'],
        'externalId': json['external_id'] == null ? undefined : json['external_id'],
        'externalSource': json['external_source'] == null ? undefined : json['external_source'],
        'id': json['id'],
        'name': json['name'],
        'parent': json['parent'] == null ? undefined : json['parent'],
        'project': json['project'],
        'sortOrder': json['sort_order'] == null ? undefined : json['sort_order'],
        'updatedAt': (new Date(json['updated_at'])),
        'updatedBy': json['updated_by'],
        'workspace': json['workspace'],
    };
}

export function LabelToJSON(json: any): Label {
    return LabelToJSONTyped(json, false);
}

export function LabelToJSONTyped(value?: Omit<Label, 'created_at'|'created_by'|'deleted_at'|'id'|'project'|'updated_at'|'updated_by'|'workspace'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'color': value['color'],
        'description': value['description'],
        'external_id': value['externalId'],
        'external_source': value['externalSource'],
        'name': value['name'],
        'parent': value['parent'],
        'sort_order': value['sortOrder'],
    };
}

