/* tslint:disable */
/* eslint-disable */
/**
 * Plane API
 * API documentation for my specific app
 *
 * The version of the OpenAPI document: 1.0.0 (1.0.0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModuleIssue
 */
export interface ModuleIssue {
    /**
     * 
     * @type {Date}
     * @memberof ModuleIssue
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof ModuleIssue
     */
    readonly createdBy: string | null;
    /**
     * 
     * @type {Date}
     * @memberof ModuleIssue
     */
    deletedAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof ModuleIssue
     */
    readonly id: string;
    /**
     * 
     * @type {string}
     * @memberof ModuleIssue
     */
    issue: string;
    /**
     * 
     * @type {string}
     * @memberof ModuleIssue
     */
    readonly module: string;
    /**
     * 
     * @type {string}
     * @memberof ModuleIssue
     */
    readonly project: string;
    /**
     * 
     * @type {number}
     * @memberof ModuleIssue
     */
    readonly subIssuesCount: number;
    /**
     * 
     * @type {Date}
     * @memberof ModuleIssue
     */
    readonly updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof ModuleIssue
     */
    readonly updatedBy: string | null;
    /**
     * 
     * @type {string}
     * @memberof ModuleIssue
     */
    readonly workspace: string;
}

/**
 * Check if a given object implements the ModuleIssue interface.
 */
export function instanceOfModuleIssue(value: object): value is ModuleIssue {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('deletedAt' in value) || value['deletedAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('issue' in value) || value['issue'] === undefined) return false;
    if (!('module' in value) || value['module'] === undefined) return false;
    if (!('project' in value) || value['project'] === undefined) return false;
    if (!('subIssuesCount' in value) || value['subIssuesCount'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('updatedBy' in value) || value['updatedBy'] === undefined) return false;
    if (!('workspace' in value) || value['workspace'] === undefined) return false;
    return true;
}

export function ModuleIssueFromJSON(json: any): ModuleIssue {
    return ModuleIssueFromJSONTyped(json, false);
}

export function ModuleIssueFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModuleIssue {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': (new Date(json['created_at'])),
        'createdBy': json['created_by'],
        'deletedAt': (json['deleted_at'] == null ? null : new Date(json['deleted_at'])),
        'id': json['id'],
        'issue': json['issue'],
        'module': json['module'],
        'project': json['project'],
        'subIssuesCount': json['sub_issues_count'],
        'updatedAt': (new Date(json['updated_at'])),
        'updatedBy': json['updated_by'],
        'workspace': json['workspace'],
    };
}

export function ModuleIssueToJSON(json: any): ModuleIssue {
    return ModuleIssueToJSONTyped(json, false);
}

export function ModuleIssueToJSONTyped(value?: Omit<ModuleIssue, 'created_at'|'created_by'|'id'|'module'|'project'|'sub_issues_count'|'updated_at'|'updated_by'|'workspace'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deleted_at': (value['deletedAt'] == null ? null : (value['deletedAt'] as any).toISOString()),
        'issue': value['issue'],
    };
}

