/* tslint:disable */
/* eslint-disable */
/**
 * Plane API
 * API documentation for my specific app
 *
 * The version of the OpenAPI document: 1.0.0 (1.0.0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StatusA3dEnum } from './StatusA3dEnum';
import {
    StatusA3dEnumFromJSON,
    StatusA3dEnumFromJSONTyped,
    StatusA3dEnumToJSON,
    StatusA3dEnumToJSONTyped,
} from './StatusA3dEnum';

/**
 * 
 * @export
 * @interface ModuleLite
 */
export interface ModuleLite {
    /**
     * 
     * @type {Date}
     * @memberof ModuleLite
     */
    archivedAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ModuleLite
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof ModuleLite
     */
    createdBy?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof ModuleLite
     */
    deletedAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof ModuleLite
     */
    description?: string;
    /**
     * 
     * @type {any}
     * @memberof ModuleLite
     */
    descriptionHtml?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ModuleLite
     */
    descriptionText?: any | null;
    /**
     * 
     * @type {string}
     * @memberof ModuleLite
     */
    externalId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ModuleLite
     */
    externalSource?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ModuleLite
     */
    readonly id: string;
    /**
     * 
     * @type {string}
     * @memberof ModuleLite
     */
    lead?: string | null;
    /**
     * 
     * @type {any}
     * @memberof ModuleLite
     */
    logoProps?: any | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ModuleLite
     */
    readonly members: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ModuleLite
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ModuleLite
     */
    project: string;
    /**
     * 
     * @type {number}
     * @memberof ModuleLite
     */
    sortOrder?: number;
    /**
     * 
     * @type {Date}
     * @memberof ModuleLite
     */
    startDate?: Date | null;
    /**
     * 
     * @type {StatusA3dEnum}
     * @memberof ModuleLite
     */
    status?: StatusA3dEnum;
    /**
     * 
     * @type {Date}
     * @memberof ModuleLite
     */
    targetDate?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ModuleLite
     */
    readonly updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof ModuleLite
     */
    updatedBy?: string | null;
    /**
     * 
     * @type {any}
     * @memberof ModuleLite
     */
    viewProps?: any | null;
    /**
     * 
     * @type {string}
     * @memberof ModuleLite
     */
    workspace: string;
}



/**
 * Check if a given object implements the ModuleLite interface.
 */
export function instanceOfModuleLite(value: object): value is ModuleLite {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('deletedAt' in value) || value['deletedAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('members' in value) || value['members'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('project' in value) || value['project'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('workspace' in value) || value['workspace'] === undefined) return false;
    return true;
}

export function ModuleLiteFromJSON(json: any): ModuleLite {
    return ModuleLiteFromJSONTyped(json, false);
}

export function ModuleLiteFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModuleLite {
    if (json == null) {
        return json;
    }
    return {
        
        'archivedAt': json['archived_at'] == null ? undefined : (new Date(json['archived_at'])),
        'createdAt': (new Date(json['created_at'])),
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
        'deletedAt': (json['deleted_at'] == null ? null : new Date(json['deleted_at'])),
        'description': json['description'] == null ? undefined : json['description'],
        'descriptionHtml': json['description_html'] == null ? undefined : json['description_html'],
        'descriptionText': json['description_text'] == null ? undefined : json['description_text'],
        'externalId': json['external_id'] == null ? undefined : json['external_id'],
        'externalSource': json['external_source'] == null ? undefined : json['external_source'],
        'id': json['id'],
        'lead': json['lead'] == null ? undefined : json['lead'],
        'logoProps': json['logo_props'] == null ? undefined : json['logo_props'],
        'members': json['members'],
        'name': json['name'],
        'project': json['project'],
        'sortOrder': json['sort_order'] == null ? undefined : json['sort_order'],
        'startDate': json['start_date'] == null ? undefined : (new Date(json['start_date'])),
        'status': json['status'] == null ? undefined : StatusA3dEnumFromJSON(json['status']),
        'targetDate': json['target_date'] == null ? undefined : (new Date(json['target_date'])),
        'updatedAt': (new Date(json['updated_at'])),
        'updatedBy': json['updated_by'] == null ? undefined : json['updated_by'],
        'viewProps': json['view_props'] == null ? undefined : json['view_props'],
        'workspace': json['workspace'],
    };
}

export function ModuleLiteToJSON(json: any): ModuleLite {
    return ModuleLiteToJSONTyped(json, false);
}

export function ModuleLiteToJSONTyped(value?: Omit<ModuleLite, 'created_at'|'id'|'members'|'updated_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'archived_at': value['archivedAt'] == null ? undefined : ((value['archivedAt'] as any).toISOString()),
        'created_by': value['createdBy'],
        'deleted_at': (value['deletedAt'] == null ? null : (value['deletedAt'] as any).toISOString()),
        'description': value['description'],
        'description_html': value['descriptionHtml'],
        'description_text': value['descriptionText'],
        'external_id': value['externalId'],
        'external_source': value['externalSource'],
        'lead': value['lead'],
        'logo_props': value['logoProps'],
        'name': value['name'],
        'project': value['project'],
        'sort_order': value['sortOrder'],
        'start_date': value['startDate'] == null ? undefined : ((value['startDate'] as any).toISOString().substring(0,10)),
        'status': StatusA3dEnumToJSON(value['status']),
        'target_date': value['targetDate'] == null ? undefined : ((value['targetDate'] as any).toISOString().substring(0,10)),
        'updated_by': value['updatedBy'],
        'view_props': value['viewProps'],
        'workspace': value['workspace'],
    };
}

