/* tslint:disable */
/* eslint-disable */
/**
 * Plane API
 * API documentation for my specific app
 *
 * The version of the OpenAPI document: 1.0.0 (1.0.0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StatusA3dEnum } from './StatusA3dEnum';
import {
    StatusA3dEnumFromJSON,
    StatusA3dEnumFromJSONTyped,
    StatusA3dEnumToJSON,
    StatusA3dEnumToJSONTyped,
} from './StatusA3dEnum';

/**
 * 
 * @export
 * @interface Module
 */
export interface Module {
    /**
     * 
     * @type {Date}
     * @memberof Module
     */
    archivedAt?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof Module
     */
    readonly backlogIssues: number;
    /**
     * 
     * @type {number}
     * @memberof Module
     */
    readonly cancelledIssues: number;
    /**
     * 
     * @type {number}
     * @memberof Module
     */
    readonly completedIssues: number;
    /**
     * 
     * @type {Date}
     * @memberof Module
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof Module
     */
    readonly createdBy: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Module
     */
    readonly deletedAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof Module
     */
    description?: string;
    /**
     * 
     * @type {any}
     * @memberof Module
     */
    descriptionHtml?: any | null;
    /**
     * 
     * @type {any}
     * @memberof Module
     */
    descriptionText?: any | null;
    /**
     * 
     * @type {string}
     * @memberof Module
     */
    externalId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Module
     */
    externalSource?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Module
     */
    readonly id: string;
    /**
     * 
     * @type {string}
     * @memberof Module
     */
    lead?: string | null;
    /**
     * 
     * @type {any}
     * @memberof Module
     */
    logoProps?: any | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof Module
     */
    members?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof Module
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Module
     */
    readonly project: string;
    /**
     * 
     * @type {number}
     * @memberof Module
     */
    sortOrder?: number;
    /**
     * 
     * @type {Date}
     * @memberof Module
     */
    startDate?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof Module
     */
    readonly startedIssues: number;
    /**
     * 
     * @type {StatusA3dEnum}
     * @memberof Module
     */
    status?: StatusA3dEnum;
    /**
     * 
     * @type {Date}
     * @memberof Module
     */
    targetDate?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof Module
     */
    readonly totalIssues: number;
    /**
     * 
     * @type {number}
     * @memberof Module
     */
    readonly unstartedIssues: number;
    /**
     * 
     * @type {Date}
     * @memberof Module
     */
    readonly updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof Module
     */
    readonly updatedBy: string | null;
    /**
     * 
     * @type {any}
     * @memberof Module
     */
    viewProps?: any | null;
    /**
     * 
     * @type {string}
     * @memberof Module
     */
    readonly workspace: string;
}



/**
 * Check if a given object implements the Module interface.
 */
export function instanceOfModule(value: object): value is Module {
    if (!('backlogIssues' in value) || value['backlogIssues'] === undefined) return false;
    if (!('cancelledIssues' in value) || value['cancelledIssues'] === undefined) return false;
    if (!('completedIssues' in value) || value['completedIssues'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('deletedAt' in value) || value['deletedAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('project' in value) || value['project'] === undefined) return false;
    if (!('startedIssues' in value) || value['startedIssues'] === undefined) return false;
    if (!('totalIssues' in value) || value['totalIssues'] === undefined) return false;
    if (!('unstartedIssues' in value) || value['unstartedIssues'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('updatedBy' in value) || value['updatedBy'] === undefined) return false;
    if (!('workspace' in value) || value['workspace'] === undefined) return false;
    return true;
}

export function ModuleFromJSON(json: any): Module {
    return ModuleFromJSONTyped(json, false);
}

export function ModuleFromJSONTyped(json: any, ignoreDiscriminator: boolean): Module {
    if (json == null) {
        return json;
    }
    return {
        
        'archivedAt': json['archived_at'] == null ? undefined : (new Date(json['archived_at'])),
        'backlogIssues': json['backlog_issues'],
        'cancelledIssues': json['cancelled_issues'],
        'completedIssues': json['completed_issues'],
        'createdAt': (new Date(json['created_at'])),
        'createdBy': json['created_by'],
        'deletedAt': (json['deleted_at'] == null ? null : new Date(json['deleted_at'])),
        'description': json['description'] == null ? undefined : json['description'],
        'descriptionHtml': json['description_html'] == null ? undefined : json['description_html'],
        'descriptionText': json['description_text'] == null ? undefined : json['description_text'],
        'externalId': json['external_id'] == null ? undefined : json['external_id'],
        'externalSource': json['external_source'] == null ? undefined : json['external_source'],
        'id': json['id'],
        'lead': json['lead'] == null ? undefined : json['lead'],
        'logoProps': json['logo_props'] == null ? undefined : json['logo_props'],
        'members': json['members'] == null ? undefined : json['members'],
        'name': json['name'],
        'project': json['project'],
        'sortOrder': json['sort_order'] == null ? undefined : json['sort_order'],
        'startDate': json['start_date'] == null ? undefined : (new Date(json['start_date'])),
        'startedIssues': json['started_issues'],
        'status': json['status'] == null ? undefined : StatusA3dEnumFromJSON(json['status']),
        'targetDate': json['target_date'] == null ? undefined : (new Date(json['target_date'])),
        'totalIssues': json['total_issues'],
        'unstartedIssues': json['unstarted_issues'],
        'updatedAt': (new Date(json['updated_at'])),
        'updatedBy': json['updated_by'],
        'viewProps': json['view_props'] == null ? undefined : json['view_props'],
        'workspace': json['workspace'],
    };
}

export function ModuleToJSON(json: any): Module {
    return ModuleToJSONTyped(json, false);
}

export function ModuleToJSONTyped(value?: Omit<Module, 'backlog_issues'|'cancelled_issues'|'completed_issues'|'created_at'|'created_by'|'deleted_at'|'id'|'project'|'started_issues'|'total_issues'|'unstarted_issues'|'updated_at'|'updated_by'|'workspace'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'archived_at': value['archivedAt'] == null ? undefined : ((value['archivedAt'] as any).toISOString()),
        'description': value['description'],
        'description_html': value['descriptionHtml'],
        'description_text': value['descriptionText'],
        'external_id': value['externalId'],
        'external_source': value['externalSource'],
        'lead': value['lead'],
        'logo_props': value['logoProps'],
        'members': value['members'],
        'name': value['name'],
        'sort_order': value['sortOrder'],
        'start_date': value['startDate'] == null ? undefined : ((value['startDate'] as any).toISOString().substring(0,10)),
        'status': StatusA3dEnumToJSON(value['status']),
        'target_date': value['targetDate'] == null ? undefined : ((value['targetDate'] as any).toISOString().substring(0,10)),
        'view_props': value['viewProps'],
    };
}

