/* tslint:disable */
/* eslint-disable */
/**
 * Plane API
 * API documentation for my specific app
 *
 * The version of the OpenAPI document: 1.0.0 (1.0.0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `0` - Secret
 * * `2` - Public
 * @export
 */
export const NetworkEnum = {
    NUMBER_0: 0,
    NUMBER_2: 2
} as const;
export type NetworkEnum = typeof NetworkEnum[keyof typeof NetworkEnum];


export function instanceOfNetworkEnum(value: any): boolean {
    for (const key in NetworkEnum) {
        if (Object.prototype.hasOwnProperty.call(NetworkEnum, key)) {
            if (NetworkEnum[key as keyof typeof NetworkEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function NetworkEnumFromJSON(json: any): NetworkEnum {
    return NetworkEnumFromJSONTyped(json, false);
}

export function NetworkEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): NetworkEnum {
    return json as NetworkEnum;
}

export function NetworkEnumToJSON(value?: NetworkEnum | null): any {
    return value as any;
}

export function NetworkEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): NetworkEnum {
    return value as NetworkEnum;
}

