/* tslint:disable */
/* eslint-disable */
/**
 * Plane API
 * API documentation for my specific app
 *
 * The version of the OpenAPI document: 1.0.0 (1.0.0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NetworkEnum } from './NetworkEnum';
import {
    NetworkEnumFromJSON,
    NetworkEnumFromJSONTyped,
    NetworkEnumToJSON,
    NetworkEnumToJSONTyped,
} from './NetworkEnum';
import type { TimezoneEnum } from './TimezoneEnum';
import {
    TimezoneEnumFromJSON,
    TimezoneEnumFromJSONTyped,
    TimezoneEnumToJSON,
    TimezoneEnumToJSONTyped,
} from './TimezoneEnum';

/**
 * 
 * @export
 * @interface PatchedProject
 */
export interface PatchedProject {
    /**
     * 
     * @type {number}
     * @memberof PatchedProject
     */
    archiveIn?: number;
    /**
     * 
     * @type {Date}
     * @memberof PatchedProject
     */
    archivedAt?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedProject
     */
    closeIn?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedProject
     */
    coverImage?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedProject
     */
    coverImageAsset?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedProject
     */
    readonly coverImageUrl?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedProject
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof PatchedProject
     */
    readonly createdBy?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedProject
     */
    cycleView?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PatchedProject
     */
    defaultAssignee?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedProject
     */
    defaultState?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof PatchedProject
     */
    readonly deletedAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedProject
     */
    description?: string;
    /**
     * 
     * @type {any}
     * @memberof PatchedProject
     */
    descriptionHtml?: any | null;
    /**
     * 
     * @type {any}
     * @memberof PatchedProject
     */
    descriptionText?: any | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedProject
     */
    readonly emoji?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedProject
     */
    estimate?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedProject
     */
    guestViewAllFeatures?: boolean;
    /**
     * 
     * @type {any}
     * @memberof PatchedProject
     */
    iconProp?: any | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedProject
     */
    readonly id?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedProject
     */
    identifier?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedProject
     */
    inboxView?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedProject
     */
    readonly isDeployed?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedProject
     */
    isIssueTypeEnabled?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedProject
     */
    readonly isMember?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedProject
     */
    isTimeTrackingEnabled?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedProject
     */
    issueViewsView?: boolean;
    /**
     * 
     * @type {any}
     * @memberof PatchedProject
     */
    logoProps?: any | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedProject
     */
    readonly memberRole?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedProject
     */
    moduleView?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PatchedProject
     */
    name?: string;
    /**
     * 
     * @type {NetworkEnum}
     * @memberof PatchedProject
     */
    network?: NetworkEnum;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedProject
     */
    pageView?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PatchedProject
     */
    projectLead?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedProject
     */
    readonly sortOrder?: number;
    /**
     * 
     * @type {TimezoneEnum}
     * @memberof PatchedProject
     */
    timezone?: TimezoneEnum;
    /**
     * 
     * @type {number}
     * @memberof PatchedProject
     */
    readonly totalCycles?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedProject
     */
    readonly totalMembers?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedProject
     */
    readonly totalModules?: number;
    /**
     * 
     * @type {Date}
     * @memberof PatchedProject
     */
    readonly updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof PatchedProject
     */
    readonly updatedBy?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedProject
     */
    readonly workspace?: string;
}



/**
 * Check if a given object implements the PatchedProject interface.
 */
export function instanceOfPatchedProject(value: object): value is PatchedProject {
    return true;
}

export function PatchedProjectFromJSON(json: any): PatchedProject {
    return PatchedProjectFromJSONTyped(json, false);
}

export function PatchedProjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedProject {
    if (json == null) {
        return json;
    }
    return {
        
        'archiveIn': json['archive_in'] == null ? undefined : json['archive_in'],
        'archivedAt': json['archived_at'] == null ? undefined : (new Date(json['archived_at'])),
        'closeIn': json['close_in'] == null ? undefined : json['close_in'],
        'coverImage': json['cover_image'] == null ? undefined : json['cover_image'],
        'coverImageAsset': json['cover_image_asset'] == null ? undefined : json['cover_image_asset'],
        'coverImageUrl': json['cover_image_url'] == null ? undefined : json['cover_image_url'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
        'cycleView': json['cycle_view'] == null ? undefined : json['cycle_view'],
        'defaultAssignee': json['default_assignee'] == null ? undefined : json['default_assignee'],
        'defaultState': json['default_state'] == null ? undefined : json['default_state'],
        'deletedAt': json['deleted_at'] == null ? undefined : (new Date(json['deleted_at'])),
        'description': json['description'] == null ? undefined : json['description'],
        'descriptionHtml': json['description_html'] == null ? undefined : json['description_html'],
        'descriptionText': json['description_text'] == null ? undefined : json['description_text'],
        'emoji': json['emoji'] == null ? undefined : json['emoji'],
        'estimate': json['estimate'] == null ? undefined : json['estimate'],
        'guestViewAllFeatures': json['guest_view_all_features'] == null ? undefined : json['guest_view_all_features'],
        'iconProp': json['icon_prop'] == null ? undefined : json['icon_prop'],
        'id': json['id'] == null ? undefined : json['id'],
        'identifier': json['identifier'] == null ? undefined : json['identifier'],
        'inboxView': json['inbox_view'] == null ? undefined : json['inbox_view'],
        'isDeployed': json['is_deployed'] == null ? undefined : json['is_deployed'],
        'isIssueTypeEnabled': json['is_issue_type_enabled'] == null ? undefined : json['is_issue_type_enabled'],
        'isMember': json['is_member'] == null ? undefined : json['is_member'],
        'isTimeTrackingEnabled': json['is_time_tracking_enabled'] == null ? undefined : json['is_time_tracking_enabled'],
        'issueViewsView': json['issue_views_view'] == null ? undefined : json['issue_views_view'],
        'logoProps': json['logo_props'] == null ? undefined : json['logo_props'],
        'memberRole': json['member_role'] == null ? undefined : json['member_role'],
        'moduleView': json['module_view'] == null ? undefined : json['module_view'],
        'name': json['name'] == null ? undefined : json['name'],
        'network': json['network'] == null ? undefined : NetworkEnumFromJSON(json['network']),
        'pageView': json['page_view'] == null ? undefined : json['page_view'],
        'projectLead': json['project_lead'] == null ? undefined : json['project_lead'],
        'sortOrder': json['sort_order'] == null ? undefined : json['sort_order'],
        'timezone': json['timezone'] == null ? undefined : TimezoneEnumFromJSON(json['timezone']),
        'totalCycles': json['total_cycles'] == null ? undefined : json['total_cycles'],
        'totalMembers': json['total_members'] == null ? undefined : json['total_members'],
        'totalModules': json['total_modules'] == null ? undefined : json['total_modules'],
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'updatedBy': json['updated_by'] == null ? undefined : json['updated_by'],
        'workspace': json['workspace'] == null ? undefined : json['workspace'],
    };
}

export function PatchedProjectToJSON(json: any): PatchedProject {
    return PatchedProjectToJSONTyped(json, false);
}

export function PatchedProjectToJSONTyped(value?: Omit<PatchedProject, 'cover_image_url'|'created_at'|'created_by'|'deleted_at'|'emoji'|'id'|'is_deployed'|'is_member'|'member_role'|'sort_order'|'total_cycles'|'total_members'|'total_modules'|'updated_at'|'updated_by'|'workspace'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'archive_in': value['archiveIn'],
        'archived_at': value['archivedAt'] == null ? undefined : ((value['archivedAt'] as any).toISOString()),
        'close_in': value['closeIn'],
        'cover_image': value['coverImage'],
        'cover_image_asset': value['coverImageAsset'],
        'cycle_view': value['cycleView'],
        'default_assignee': value['defaultAssignee'],
        'default_state': value['defaultState'],
        'description': value['description'],
        'description_html': value['descriptionHtml'],
        'description_text': value['descriptionText'],
        'estimate': value['estimate'],
        'guest_view_all_features': value['guestViewAllFeatures'],
        'icon_prop': value['iconProp'],
        'identifier': value['identifier'],
        'inbox_view': value['inboxView'],
        'is_issue_type_enabled': value['isIssueTypeEnabled'],
        'is_time_tracking_enabled': value['isTimeTrackingEnabled'],
        'issue_views_view': value['issueViewsView'],
        'logo_props': value['logoProps'],
        'module_view': value['moduleView'],
        'name': value['name'],
        'network': NetworkEnumToJSON(value['network']),
        'page_view': value['pageView'],
        'project_lead': value['projectLead'],
        'timezone': TimezoneEnumToJSON(value['timezone']),
    };
}

