/* tslint:disable */
/* eslint-disable */
/**
 * Plane API
 * API documentation for my specific app
 *
 * The version of the OpenAPI document: 1.0.0 (1.0.0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IssueExpand } from './IssueExpand';
import {
    IssueExpandFromJSON,
    IssueExpandFromJSONTyped,
    IssueExpandToJSON,
    IssueExpandToJSONTyped,
} from './IssueExpand';
import type { InboxIssueStatusEnum } from './InboxIssueStatusEnum';
import {
    InboxIssueStatusEnumFromJSON,
    InboxIssueStatusEnumFromJSONTyped,
    InboxIssueStatusEnumToJSON,
    InboxIssueStatusEnumToJSONTyped,
} from './InboxIssueStatusEnum';

/**
 * 
 * @export
 * @interface PatchedInboxIssue
 */
export interface PatchedInboxIssue {
    /**
     * 
     * @type {Date}
     * @memberof PatchedInboxIssue
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof PatchedInboxIssue
     */
    readonly createdBy?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof PatchedInboxIssue
     */
    deletedAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedInboxIssue
     */
    duplicateTo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedInboxIssue
     */
    externalId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedInboxIssue
     */
    externalSource?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedInboxIssue
     */
    readonly id?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedInboxIssue
     */
    inbox?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedInboxIssue
     */
    readonly issue?: string;
    /**
     * 
     * @type {IssueExpand}
     * @memberof PatchedInboxIssue
     */
    readonly issueDetail?: IssueExpand;
    /**
     * 
     * @type {string}
     * @memberof PatchedInboxIssue
     */
    readonly project?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedInboxIssue
     */
    snoozedTill?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedInboxIssue
     */
    source?: string | null;
    /**
     * 
     * @type {InboxIssueStatusEnum}
     * @memberof PatchedInboxIssue
     */
    status?: InboxIssueStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof PatchedInboxIssue
     */
    readonly updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof PatchedInboxIssue
     */
    readonly updatedBy?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedInboxIssue
     */
    readonly workspace?: string;
}



/**
 * Check if a given object implements the PatchedInboxIssue interface.
 */
export function instanceOfPatchedInboxIssue(value: object): value is PatchedInboxIssue {
    return true;
}

export function PatchedInboxIssueFromJSON(json: any): PatchedInboxIssue {
    return PatchedInboxIssueFromJSONTyped(json, false);
}

export function PatchedInboxIssueFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedInboxIssue {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
        'deletedAt': json['deleted_at'] == null ? undefined : (new Date(json['deleted_at'])),
        'duplicateTo': json['duplicate_to'] == null ? undefined : json['duplicate_to'],
        'externalId': json['external_id'] == null ? undefined : json['external_id'],
        'externalSource': json['external_source'] == null ? undefined : json['external_source'],
        'id': json['id'] == null ? undefined : json['id'],
        'inbox': json['inbox'] == null ? undefined : json['inbox'],
        'issue': json['issue'] == null ? undefined : json['issue'],
        'issueDetail': json['issue_detail'] == null ? undefined : IssueExpandFromJSON(json['issue_detail']),
        'project': json['project'] == null ? undefined : json['project'],
        'snoozedTill': json['snoozed_till'] == null ? undefined : (new Date(json['snoozed_till'])),
        'source': json['source'] == null ? undefined : json['source'],
        'status': json['status'] == null ? undefined : InboxIssueStatusEnumFromJSON(json['status']),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'updatedBy': json['updated_by'] == null ? undefined : json['updated_by'],
        'workspace': json['workspace'] == null ? undefined : json['workspace'],
    };
}

export function PatchedInboxIssueToJSON(json: any): PatchedInboxIssue {
    return PatchedInboxIssueToJSONTyped(json, false);
}

export function PatchedInboxIssueToJSONTyped(value?: Omit<PatchedInboxIssue, 'created_at'|'created_by'|'id'|'issue'|'issue_detail'|'project'|'updated_at'|'updated_by'|'workspace'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deleted_at': value['deletedAt'] == null ? undefined : ((value['deletedAt'] as any).toISOString()),
        'duplicate_to': value['duplicateTo'],
        'external_id': value['externalId'],
        'external_source': value['externalSource'],
        'inbox': value['inbox'],
        'snoozed_till': value['snoozedTill'] == null ? undefined : ((value['snoozedTill'] as any).toISOString()),
        'source': value['source'],
        'status': InboxIssueStatusEnumToJSON(value['status']),
    };
}

