/* tslint:disable */
/* eslint-disable */
/**
 * Plane API
 * API documentation for my specific app
 *
 * The version of the OpenAPI document: 1.0.0 (1.0.0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedLabel
 */
export interface PatchedLabel {
    /**
     * 
     * @type {string}
     * @memberof PatchedLabel
     */
    color?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedLabel
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof PatchedLabel
     */
    readonly createdBy?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof PatchedLabel
     */
    readonly deletedAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedLabel
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedLabel
     */
    externalId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedLabel
     */
    externalSource?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedLabel
     */
    readonly id?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedLabel
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedLabel
     */
    parent?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedLabel
     */
    readonly project?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchedLabel
     */
    sortOrder?: number;
    /**
     * 
     * @type {Date}
     * @memberof PatchedLabel
     */
    readonly updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof PatchedLabel
     */
    readonly updatedBy?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedLabel
     */
    readonly workspace?: string;
}

/**
 * Check if a given object implements the PatchedLabel interface.
 */
export function instanceOfPatchedLabel(value: object): value is PatchedLabel {
    return true;
}

export function PatchedLabelFromJSON(json: any): PatchedLabel {
    return PatchedLabelFromJSONTyped(json, false);
}

export function PatchedLabelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedLabel {
    if (json == null) {
        return json;
    }
    return {
        
        'color': json['color'] == null ? undefined : json['color'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
        'deletedAt': json['deleted_at'] == null ? undefined : (new Date(json['deleted_at'])),
        'description': json['description'] == null ? undefined : json['description'],
        'externalId': json['external_id'] == null ? undefined : json['external_id'],
        'externalSource': json['external_source'] == null ? undefined : json['external_source'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'parent': json['parent'] == null ? undefined : json['parent'],
        'project': json['project'] == null ? undefined : json['project'],
        'sortOrder': json['sort_order'] == null ? undefined : json['sort_order'],
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'updatedBy': json['updated_by'] == null ? undefined : json['updated_by'],
        'workspace': json['workspace'] == null ? undefined : json['workspace'],
    };
}

export function PatchedLabelToJSON(json: any): PatchedLabel {
    return PatchedLabelToJSONTyped(json, false);
}

export function PatchedLabelToJSONTyped(value?: Omit<PatchedLabel, 'created_at'|'created_by'|'deleted_at'|'id'|'project'|'updated_at'|'updated_by'|'workspace'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'color': value['color'],
        'description': value['description'],
        'external_id': value['externalId'],
        'external_source': value['externalSource'],
        'name': value['name'],
        'parent': value['parent'],
        'sort_order': value['sortOrder'],
    };
}

