/* tslint:disable */
/* eslint-disable */
/**
 * Plane API
 * API documentation for my specific app
 *
 * The version of the OpenAPI document: 1.0.0 (1.0.0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedIssueTypeAPI
 */
export interface PatchedIssueTypeAPI {
    /**
     * 
     * @type {Date}
     * @memberof PatchedIssueTypeAPI
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof PatchedIssueTypeAPI
     */
    readonly createdBy?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof PatchedIssueTypeAPI
     */
    readonly deletedAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedIssueTypeAPI
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedIssueTypeAPI
     */
    externalId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedIssueTypeAPI
     */
    externalSource?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedIssueTypeAPI
     */
    readonly id?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedIssueTypeAPI
     */
    isActive?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedIssueTypeAPI
     */
    readonly isDefault?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PatchedIssueTypeAPI
     */
    readonly level?: number;
    /**
     * 
     * @type {any}
     * @memberof PatchedIssueTypeAPI
     */
    readonly logoProps?: any | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedIssueTypeAPI
     */
    name?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof PatchedIssueTypeAPI
     */
    projectIds?: Array<string>;
    /**
     * 
     * @type {Date}
     * @memberof PatchedIssueTypeAPI
     */
    readonly updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof PatchedIssueTypeAPI
     */
    readonly updatedBy?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedIssueTypeAPI
     */
    readonly workspace?: string;
}

/**
 * Check if a given object implements the PatchedIssueTypeAPI interface.
 */
export function instanceOfPatchedIssueTypeAPI(value: object): value is PatchedIssueTypeAPI {
    return true;
}

export function PatchedIssueTypeAPIFromJSON(json: any): PatchedIssueTypeAPI {
    return PatchedIssueTypeAPIFromJSONTyped(json, false);
}

export function PatchedIssueTypeAPIFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedIssueTypeAPI {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
        'deletedAt': json['deleted_at'] == null ? undefined : (new Date(json['deleted_at'])),
        'description': json['description'] == null ? undefined : json['description'],
        'externalId': json['external_id'] == null ? undefined : json['external_id'],
        'externalSource': json['external_source'] == null ? undefined : json['external_source'],
        'id': json['id'] == null ? undefined : json['id'],
        'isActive': json['is_active'] == null ? undefined : json['is_active'],
        'isDefault': json['is_default'] == null ? undefined : json['is_default'],
        'level': json['level'] == null ? undefined : json['level'],
        'logoProps': json['logo_props'] == null ? undefined : json['logo_props'],
        'name': json['name'] == null ? undefined : json['name'],
        'projectIds': json['project_ids'] == null ? undefined : json['project_ids'],
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'updatedBy': json['updated_by'] == null ? undefined : json['updated_by'],
        'workspace': json['workspace'] == null ? undefined : json['workspace'],
    };
}

export function PatchedIssueTypeAPIToJSON(json: any): PatchedIssueTypeAPI {
    return PatchedIssueTypeAPIToJSONTyped(json, false);
}

export function PatchedIssueTypeAPIToJSONTyped(value?: Omit<PatchedIssueTypeAPI, 'created_at'|'created_by'|'deleted_at'|'id'|'is_default'|'level'|'logo_props'|'updated_at'|'updated_by'|'workspace'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'external_id': value['externalId'],
        'external_source': value['externalSource'],
        'is_active': value['isActive'],
        'name': value['name'],
        'project_ids': value['projectIds'],
    };
}

