/* tslint:disable */
/* eslint-disable */
/**
 * Plane API
 * API documentation for my specific app
 *
 * The version of the OpenAPI document: 1.0.0 (1.0.0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedIssuePropertyOptionAPI
 */
export interface PatchedIssuePropertyOptionAPI {
    /**
     * 
     * @type {Date}
     * @memberof PatchedIssuePropertyOptionAPI
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof PatchedIssuePropertyOptionAPI
     */
    readonly createdBy?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof PatchedIssuePropertyOptionAPI
     */
    readonly deletedAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedIssuePropertyOptionAPI
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedIssuePropertyOptionAPI
     */
    externalId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedIssuePropertyOptionAPI
     */
    externalSource?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedIssuePropertyOptionAPI
     */
    readonly id?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedIssuePropertyOptionAPI
     */
    isActive?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedIssuePropertyOptionAPI
     */
    isDefault?: boolean;
    /**
     * 
     * @type {any}
     * @memberof PatchedIssuePropertyOptionAPI
     */
    readonly logoProps?: any | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedIssuePropertyOptionAPI
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedIssuePropertyOptionAPI
     */
    parent?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedIssuePropertyOptionAPI
     */
    readonly project?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedIssuePropertyOptionAPI
     */
    readonly property?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchedIssuePropertyOptionAPI
     */
    readonly sortOrder?: number;
    /**
     * 
     * @type {Date}
     * @memberof PatchedIssuePropertyOptionAPI
     */
    readonly updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof PatchedIssuePropertyOptionAPI
     */
    readonly updatedBy?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedIssuePropertyOptionAPI
     */
    readonly workspace?: string;
}

/**
 * Check if a given object implements the PatchedIssuePropertyOptionAPI interface.
 */
export function instanceOfPatchedIssuePropertyOptionAPI(value: object): value is PatchedIssuePropertyOptionAPI {
    return true;
}

export function PatchedIssuePropertyOptionAPIFromJSON(json: any): PatchedIssuePropertyOptionAPI {
    return PatchedIssuePropertyOptionAPIFromJSONTyped(json, false);
}

export function PatchedIssuePropertyOptionAPIFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedIssuePropertyOptionAPI {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
        'deletedAt': json['deleted_at'] == null ? undefined : (new Date(json['deleted_at'])),
        'description': json['description'] == null ? undefined : json['description'],
        'externalId': json['external_id'] == null ? undefined : json['external_id'],
        'externalSource': json['external_source'] == null ? undefined : json['external_source'],
        'id': json['id'] == null ? undefined : json['id'],
        'isActive': json['is_active'] == null ? undefined : json['is_active'],
        'isDefault': json['is_default'] == null ? undefined : json['is_default'],
        'logoProps': json['logo_props'] == null ? undefined : json['logo_props'],
        'name': json['name'] == null ? undefined : json['name'],
        'parent': json['parent'] == null ? undefined : json['parent'],
        'project': json['project'] == null ? undefined : json['project'],
        'property': json['property'] == null ? undefined : json['property'],
        'sortOrder': json['sort_order'] == null ? undefined : json['sort_order'],
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'updatedBy': json['updated_by'] == null ? undefined : json['updated_by'],
        'workspace': json['workspace'] == null ? undefined : json['workspace'],
    };
}

export function PatchedIssuePropertyOptionAPIToJSON(json: any): PatchedIssuePropertyOptionAPI {
    return PatchedIssuePropertyOptionAPIToJSONTyped(json, false);
}

export function PatchedIssuePropertyOptionAPIToJSONTyped(value?: Omit<PatchedIssuePropertyOptionAPI, 'created_at'|'created_by'|'deleted_at'|'id'|'logo_props'|'project'|'property'|'sort_order'|'updated_at'|'updated_by'|'workspace'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'external_id': value['externalId'],
        'external_source': value['externalSource'],
        'is_active': value['isActive'],
        'is_default': value['isDefault'],
        'name': value['name'],
        'parent': value['parent'],
    };
}

