/* tslint:disable */
/* eslint-disable */
/**
 * Plane API
 * API documentation for my specific app
 *
 * The version of the OpenAPI document: 1.0.0 (1.0.0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GroupEnum } from './GroupEnum';
import {
    GroupEnumFromJSON,
    GroupEnumFromJSONTyped,
    GroupEnumToJSON,
    GroupEnumToJSONTyped,
} from './GroupEnum';

/**
 * 
 * @export
 * @interface PatchedState
 */
export interface PatchedState {
    /**
     * 
     * @type {string}
     * @memberof PatchedState
     */
    color?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedState
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof PatchedState
     */
    readonly createdBy?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedState
     */
    _default?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof PatchedState
     */
    readonly deletedAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedState
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedState
     */
    externalId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedState
     */
    externalSource?: string | null;
    /**
     * 
     * @type {GroupEnum}
     * @memberof PatchedState
     */
    group?: GroupEnum;
    /**
     * 
     * @type {string}
     * @memberof PatchedState
     */
    readonly id?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedState
     */
    isTriage?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PatchedState
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedState
     */
    readonly project?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchedState
     */
    sequence?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedState
     */
    slug?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedState
     */
    readonly updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof PatchedState
     */
    readonly updatedBy?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedState
     */
    readonly workspace?: string;
}



/**
 * Check if a given object implements the PatchedState interface.
 */
export function instanceOfPatchedState(value: object): value is PatchedState {
    return true;
}

export function PatchedStateFromJSON(json: any): PatchedState {
    return PatchedStateFromJSONTyped(json, false);
}

export function PatchedStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedState {
    if (json == null) {
        return json;
    }
    return {
        
        'color': json['color'] == null ? undefined : json['color'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
        '_default': json['default'] == null ? undefined : json['default'],
        'deletedAt': json['deleted_at'] == null ? undefined : (new Date(json['deleted_at'])),
        'description': json['description'] == null ? undefined : json['description'],
        'externalId': json['external_id'] == null ? undefined : json['external_id'],
        'externalSource': json['external_source'] == null ? undefined : json['external_source'],
        'group': json['group'] == null ? undefined : GroupEnumFromJSON(json['group']),
        'id': json['id'] == null ? undefined : json['id'],
        'isTriage': json['is_triage'] == null ? undefined : json['is_triage'],
        'name': json['name'] == null ? undefined : json['name'],
        'project': json['project'] == null ? undefined : json['project'],
        'sequence': json['sequence'] == null ? undefined : json['sequence'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'updatedBy': json['updated_by'] == null ? undefined : json['updated_by'],
        'workspace': json['workspace'] == null ? undefined : json['workspace'],
    };
}

export function PatchedStateToJSON(json: any): PatchedState {
    return PatchedStateToJSONTyped(json, false);
}

export function PatchedStateToJSONTyped(value?: Omit<PatchedState, 'created_at'|'created_by'|'deleted_at'|'id'|'project'|'updated_at'|'updated_by'|'workspace'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'color': value['color'],
        'default': value['_default'],
        'description': value['description'],
        'external_id': value['externalId'],
        'external_source': value['externalSource'],
        'group': GroupEnumToJSON(value['group']),
        'is_triage': value['isTriage'],
        'name': value['name'],
        'sequence': value['sequence'],
        'slug': value['slug'],
    };
}

