/* tslint:disable */
/* eslint-disable */
/**
 * Plane API
 * API documentation for my specific app
 *
 * The version of the OpenAPI document: 1.0.0 (1.0.0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PriorityEnum } from './PriorityEnum';
import {
    PriorityEnumFromJSON,
    PriorityEnumFromJSONTyped,
    PriorityEnumToJSON,
    PriorityEnumToJSONTyped,
} from './PriorityEnum';

/**
 * 
 * @export
 * @interface PatchedIssue
 */
export interface PatchedIssue {
    /**
     * 
     * @type {Date}
     * @memberof PatchedIssue
     */
    archivedAt?: Date | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof PatchedIssue
     */
    assignees?: Array<string>;
    /**
     * 
     * @type {Date}
     * @memberof PatchedIssue
     */
    completedAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof PatchedIssue
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof PatchedIssue
     */
    createdBy?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof PatchedIssue
     */
    deletedAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedIssue
     */
    readonly descriptionBinary?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedIssue
     */
    descriptionHtml?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedIssue
     */
    estimatePoint?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedIssue
     */
    externalId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedIssue
     */
    externalSource?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedIssue
     */
    readonly id?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedIssue
     */
    isDraft?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof PatchedIssue
     */
    labels?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof PatchedIssue
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedIssue
     */
    parent?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedIssue
     */
    point?: number | null;
    /**
     * 
     * @type {PriorityEnum}
     * @memberof PatchedIssue
     */
    priority?: PriorityEnum;
    /**
     * 
     * @type {string}
     * @memberof PatchedIssue
     */
    readonly project?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchedIssue
     */
    sequenceId?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedIssue
     */
    sortOrder?: number;
    /**
     * 
     * @type {Date}
     * @memberof PatchedIssue
     */
    startDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedIssue
     */
    state?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof PatchedIssue
     */
    targetDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedIssue
     */
    type?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedIssue
     */
    typeId?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof PatchedIssue
     */
    readonly updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof PatchedIssue
     */
    readonly updatedBy?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedIssue
     */
    readonly workspace?: string;
}



/**
 * Check if a given object implements the PatchedIssue interface.
 */
export function instanceOfPatchedIssue(value: object): value is PatchedIssue {
    return true;
}

export function PatchedIssueFromJSON(json: any): PatchedIssue {
    return PatchedIssueFromJSONTyped(json, false);
}

export function PatchedIssueFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedIssue {
    if (json == null) {
        return json;
    }
    return {
        
        'archivedAt': json['archived_at'] == null ? undefined : (new Date(json['archived_at'])),
        'assignees': json['assignees'] == null ? undefined : json['assignees'],
        'completedAt': json['completed_at'] == null ? undefined : (new Date(json['completed_at'])),
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
        'deletedAt': json['deleted_at'] == null ? undefined : (new Date(json['deleted_at'])),
        'descriptionBinary': json['description_binary'] == null ? undefined : json['description_binary'],
        'descriptionHtml': json['description_html'] == null ? undefined : json['description_html'],
        'estimatePoint': json['estimate_point'] == null ? undefined : json['estimate_point'],
        'externalId': json['external_id'] == null ? undefined : json['external_id'],
        'externalSource': json['external_source'] == null ? undefined : json['external_source'],
        'id': json['id'] == null ? undefined : json['id'],
        'isDraft': json['is_draft'] == null ? undefined : json['is_draft'],
        'labels': json['labels'] == null ? undefined : json['labels'],
        'name': json['name'] == null ? undefined : json['name'],
        'parent': json['parent'] == null ? undefined : json['parent'],
        'point': json['point'] == null ? undefined : json['point'],
        'priority': json['priority'] == null ? undefined : PriorityEnumFromJSON(json['priority']),
        'project': json['project'] == null ? undefined : json['project'],
        'sequenceId': json['sequence_id'] == null ? undefined : json['sequence_id'],
        'sortOrder': json['sort_order'] == null ? undefined : json['sort_order'],
        'startDate': json['start_date'] == null ? undefined : (new Date(json['start_date'])),
        'state': json['state'] == null ? undefined : json['state'],
        'targetDate': json['target_date'] == null ? undefined : (new Date(json['target_date'])),
        'type': json['type'] == null ? undefined : json['type'],
        'typeId': json['type_id'] == null ? undefined : json['type_id'],
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'updatedBy': json['updated_by'] == null ? undefined : json['updated_by'],
        'workspace': json['workspace'] == null ? undefined : json['workspace'],
    };
}

export function PatchedIssueToJSON(json: any): PatchedIssue {
    return PatchedIssueToJSONTyped(json, false);
}

export function PatchedIssueToJSONTyped(value?: Omit<PatchedIssue, 'created_at'|'description_binary'|'id'|'project'|'updated_at'|'updated_by'|'workspace'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'archived_at': value['archivedAt'] == null ? undefined : ((value['archivedAt'] as any).toISOString().substring(0,10)),
        'assignees': value['assignees'],
        'completed_at': value['completedAt'] == null ? undefined : ((value['completedAt'] as any).toISOString()),
        'created_by': value['createdBy'],
        'deleted_at': value['deletedAt'] == null ? undefined : ((value['deletedAt'] as any).toISOString()),
        'description_html': value['descriptionHtml'],
        'estimate_point': value['estimatePoint'],
        'external_id': value['externalId'],
        'external_source': value['externalSource'],
        'is_draft': value['isDraft'],
        'labels': value['labels'],
        'name': value['name'],
        'parent': value['parent'],
        'point': value['point'],
        'priority': PriorityEnumToJSON(value['priority']),
        'sequence_id': value['sequenceId'],
        'sort_order': value['sortOrder'],
        'start_date': value['startDate'] == null ? undefined : ((value['startDate'] as any).toISOString().substring(0,10)),
        'state': value['state'],
        'target_date': value['targetDate'] == null ? undefined : ((value['targetDate'] as any).toISOString().substring(0,10)),
        'type': value['type'],
        'type_id': value['typeId'],
    };
}

