/* tslint:disable */
/* eslint-disable */
/**
 * Plane API
 * API documentation for my specific app
 *
 * The version of the OpenAPI document: 1.0.0 (1.0.0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StatusA3dEnum } from './StatusA3dEnum';
import {
    StatusA3dEnumFromJSON,
    StatusA3dEnumFromJSONTyped,
    StatusA3dEnumToJSON,
    StatusA3dEnumToJSONTyped,
} from './StatusA3dEnum';

/**
 * 
 * @export
 * @interface PatchedModule
 */
export interface PatchedModule {
    /**
     * 
     * @type {Date}
     * @memberof PatchedModule
     */
    archivedAt?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedModule
     */
    readonly backlogIssues?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedModule
     */
    readonly cancelledIssues?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedModule
     */
    readonly completedIssues?: number;
    /**
     * 
     * @type {Date}
     * @memberof PatchedModule
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof PatchedModule
     */
    readonly createdBy?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof PatchedModule
     */
    readonly deletedAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedModule
     */
    description?: string;
    /**
     * 
     * @type {any}
     * @memberof PatchedModule
     */
    descriptionHtml?: any | null;
    /**
     * 
     * @type {any}
     * @memberof PatchedModule
     */
    descriptionText?: any | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedModule
     */
    externalId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedModule
     */
    externalSource?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedModule
     */
    readonly id?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedModule
     */
    lead?: string | null;
    /**
     * 
     * @type {any}
     * @memberof PatchedModule
     */
    logoProps?: any | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof PatchedModule
     */
    members?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof PatchedModule
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedModule
     */
    readonly project?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchedModule
     */
    sortOrder?: number;
    /**
     * 
     * @type {Date}
     * @memberof PatchedModule
     */
    startDate?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedModule
     */
    readonly startedIssues?: number;
    /**
     * 
     * @type {StatusA3dEnum}
     * @memberof PatchedModule
     */
    status?: StatusA3dEnum;
    /**
     * 
     * @type {Date}
     * @memberof PatchedModule
     */
    targetDate?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedModule
     */
    readonly totalIssues?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedModule
     */
    readonly unstartedIssues?: number;
    /**
     * 
     * @type {Date}
     * @memberof PatchedModule
     */
    readonly updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof PatchedModule
     */
    readonly updatedBy?: string | null;
    /**
     * 
     * @type {any}
     * @memberof PatchedModule
     */
    viewProps?: any | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedModule
     */
    readonly workspace?: string;
}



/**
 * Check if a given object implements the PatchedModule interface.
 */
export function instanceOfPatchedModule(value: object): value is PatchedModule {
    return true;
}

export function PatchedModuleFromJSON(json: any): PatchedModule {
    return PatchedModuleFromJSONTyped(json, false);
}

export function PatchedModuleFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedModule {
    if (json == null) {
        return json;
    }
    return {
        
        'archivedAt': json['archived_at'] == null ? undefined : (new Date(json['archived_at'])),
        'backlogIssues': json['backlog_issues'] == null ? undefined : json['backlog_issues'],
        'cancelledIssues': json['cancelled_issues'] == null ? undefined : json['cancelled_issues'],
        'completedIssues': json['completed_issues'] == null ? undefined : json['completed_issues'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
        'deletedAt': json['deleted_at'] == null ? undefined : (new Date(json['deleted_at'])),
        'description': json['description'] == null ? undefined : json['description'],
        'descriptionHtml': json['description_html'] == null ? undefined : json['description_html'],
        'descriptionText': json['description_text'] == null ? undefined : json['description_text'],
        'externalId': json['external_id'] == null ? undefined : json['external_id'],
        'externalSource': json['external_source'] == null ? undefined : json['external_source'],
        'id': json['id'] == null ? undefined : json['id'],
        'lead': json['lead'] == null ? undefined : json['lead'],
        'logoProps': json['logo_props'] == null ? undefined : json['logo_props'],
        'members': json['members'] == null ? undefined : json['members'],
        'name': json['name'] == null ? undefined : json['name'],
        'project': json['project'] == null ? undefined : json['project'],
        'sortOrder': json['sort_order'] == null ? undefined : json['sort_order'],
        'startDate': json['start_date'] == null ? undefined : (new Date(json['start_date'])),
        'startedIssues': json['started_issues'] == null ? undefined : json['started_issues'],
        'status': json['status'] == null ? undefined : StatusA3dEnumFromJSON(json['status']),
        'targetDate': json['target_date'] == null ? undefined : (new Date(json['target_date'])),
        'totalIssues': json['total_issues'] == null ? undefined : json['total_issues'],
        'unstartedIssues': json['unstarted_issues'] == null ? undefined : json['unstarted_issues'],
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'updatedBy': json['updated_by'] == null ? undefined : json['updated_by'],
        'viewProps': json['view_props'] == null ? undefined : json['view_props'],
        'workspace': json['workspace'] == null ? undefined : json['workspace'],
    };
}

export function PatchedModuleToJSON(json: any): PatchedModule {
    return PatchedModuleToJSONTyped(json, false);
}

export function PatchedModuleToJSONTyped(value?: Omit<PatchedModule, 'backlog_issues'|'cancelled_issues'|'completed_issues'|'created_at'|'created_by'|'deleted_at'|'id'|'project'|'started_issues'|'total_issues'|'unstarted_issues'|'updated_at'|'updated_by'|'workspace'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'archived_at': value['archivedAt'] == null ? undefined : ((value['archivedAt'] as any).toISOString()),
        'description': value['description'],
        'description_html': value['descriptionHtml'],
        'description_text': value['descriptionText'],
        'external_id': value['externalId'],
        'external_source': value['externalSource'],
        'lead': value['lead'],
        'logo_props': value['logoProps'],
        'members': value['members'],
        'name': value['name'],
        'sort_order': value['sortOrder'],
        'start_date': value['startDate'] == null ? undefined : ((value['startDate'] as any).toISOString().substring(0,10)),
        'status': StatusA3dEnumToJSON(value['status']),
        'target_date': value['targetDate'] == null ? undefined : ((value['targetDate'] as any).toISOString().substring(0,10)),
        'view_props': value['viewProps'],
    };
}

