/* tslint:disable */
/* eslint-disable */
/**
 * Plane API
 * API documentation for my specific app
 *
 * The version of the OpenAPI document: 1.0.0 (1.0.0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccessEnum } from './AccessEnum';
import {
    AccessEnumFromJSON,
    AccessEnumFromJSONTyped,
    AccessEnumToJSON,
    AccessEnumToJSONTyped,
} from './AccessEnum';

/**
 * 
 * @export
 * @interface PatchedIssueComment
 */
export interface PatchedIssueComment {
    /**
     * 
     * @type {AccessEnum}
     * @memberof PatchedIssueComment
     */
    access?: AccessEnum;
    /**
     * 
     * @type {string}
     * @memberof PatchedIssueComment
     */
    actor?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof PatchedIssueComment
     */
    attachments?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof PatchedIssueComment
     */
    commentHtml?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedIssueComment
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof PatchedIssueComment
     */
    readonly createdBy?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof PatchedIssueComment
     */
    deletedAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedIssueComment
     */
    externalId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedIssueComment
     */
    externalSource?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedIssueComment
     */
    readonly id?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedIssueComment
     */
    readonly isMember?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PatchedIssueComment
     */
    readonly issue?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedIssueComment
     */
    readonly project?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedIssueComment
     */
    readonly updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof PatchedIssueComment
     */
    readonly updatedBy?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedIssueComment
     */
    readonly workspace?: string;
}



/**
 * Check if a given object implements the PatchedIssueComment interface.
 */
export function instanceOfPatchedIssueComment(value: object): value is PatchedIssueComment {
    return true;
}

export function PatchedIssueCommentFromJSON(json: any): PatchedIssueComment {
    return PatchedIssueCommentFromJSONTyped(json, false);
}

export function PatchedIssueCommentFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedIssueComment {
    if (json == null) {
        return json;
    }
    return {
        
        'access': json['access'] == null ? undefined : AccessEnumFromJSON(json['access']),
        'actor': json['actor'] == null ? undefined : json['actor'],
        'attachments': json['attachments'] == null ? undefined : json['attachments'],
        'commentHtml': json['comment_html'] == null ? undefined : json['comment_html'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
        'deletedAt': json['deleted_at'] == null ? undefined : (new Date(json['deleted_at'])),
        'externalId': json['external_id'] == null ? undefined : json['external_id'],
        'externalSource': json['external_source'] == null ? undefined : json['external_source'],
        'id': json['id'] == null ? undefined : json['id'],
        'isMember': json['is_member'] == null ? undefined : json['is_member'],
        'issue': json['issue'] == null ? undefined : json['issue'],
        'project': json['project'] == null ? undefined : json['project'],
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'updatedBy': json['updated_by'] == null ? undefined : json['updated_by'],
        'workspace': json['workspace'] == null ? undefined : json['workspace'],
    };
}

export function PatchedIssueCommentToJSON(json: any): PatchedIssueComment {
    return PatchedIssueCommentToJSONTyped(json, false);
}

export function PatchedIssueCommentToJSONTyped(value?: Omit<PatchedIssueComment, 'created_at'|'created_by'|'id'|'is_member'|'issue'|'project'|'updated_at'|'updated_by'|'workspace'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'access': AccessEnumToJSON(value['access']),
        'actor': value['actor'],
        'attachments': value['attachments'],
        'comment_html': value['commentHtml'],
        'deleted_at': value['deletedAt'] == null ? undefined : ((value['deletedAt'] as any).toISOString()),
        'external_id': value['externalId'],
        'external_source': value['externalSource'],
    };
}

