/* tslint:disable */
/* eslint-disable */
/**
 * Plane API
 * API documentation for my specific app
 *
 * The version of the OpenAPI document: 1.0.0 (1.0.0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NetworkEnum } from './NetworkEnum';
import {
    NetworkEnumFromJSON,
    NetworkEnumFromJSONTyped,
    NetworkEnumToJSON,
    NetworkEnumToJSONTyped,
} from './NetworkEnum';
import type { TimezoneEnum } from './TimezoneEnum';
import {
    TimezoneEnumFromJSON,
    TimezoneEnumFromJSONTyped,
    TimezoneEnumToJSON,
    TimezoneEnumToJSONTyped,
} from './TimezoneEnum';

/**
 * 
 * @export
 * @interface Project
 */
export interface Project {
    /**
     * 
     * @type {number}
     * @memberof Project
     */
    archiveIn?: number;
    /**
     * 
     * @type {Date}
     * @memberof Project
     */
    archivedAt?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof Project
     */
    closeIn?: number;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    coverImage?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    coverImageAsset?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    readonly coverImageUrl: string;
    /**
     * 
     * @type {Date}
     * @memberof Project
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    readonly createdBy: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof Project
     */
    cycleView?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    defaultAssignee?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    defaultState?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Project
     */
    readonly deletedAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    description?: string;
    /**
     * 
     * @type {any}
     * @memberof Project
     */
    descriptionHtml?: any | null;
    /**
     * 
     * @type {any}
     * @memberof Project
     */
    descriptionText?: any | null;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    readonly emoji: string | null;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    estimate?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof Project
     */
    guestViewAllFeatures?: boolean;
    /**
     * 
     * @type {any}
     * @memberof Project
     */
    iconProp?: any | null;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    readonly id: string;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    identifier: string;
    /**
     * 
     * @type {boolean}
     * @memberof Project
     */
    inboxView?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Project
     */
    readonly isDeployed: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Project
     */
    isIssueTypeEnabled?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Project
     */
    readonly isMember: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Project
     */
    isTimeTrackingEnabled?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Project
     */
    issueViewsView?: boolean;
    /**
     * 
     * @type {any}
     * @memberof Project
     */
    logoProps?: any | null;
    /**
     * 
     * @type {number}
     * @memberof Project
     */
    readonly memberRole: number;
    /**
     * 
     * @type {boolean}
     * @memberof Project
     */
    moduleView?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    name: string;
    /**
     * 
     * @type {NetworkEnum}
     * @memberof Project
     */
    network?: NetworkEnum;
    /**
     * 
     * @type {boolean}
     * @memberof Project
     */
    pageView?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    projectLead?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Project
     */
    readonly sortOrder: number;
    /**
     * 
     * @type {TimezoneEnum}
     * @memberof Project
     */
    timezone?: TimezoneEnum;
    /**
     * 
     * @type {number}
     * @memberof Project
     */
    readonly totalCycles: number;
    /**
     * 
     * @type {number}
     * @memberof Project
     */
    readonly totalMembers: number;
    /**
     * 
     * @type {number}
     * @memberof Project
     */
    readonly totalModules: number;
    /**
     * 
     * @type {Date}
     * @memberof Project
     */
    readonly updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    readonly updatedBy: string | null;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    readonly workspace: string;
}



/**
 * Check if a given object implements the Project interface.
 */
export function instanceOfProject(value: object): value is Project {
    if (!('coverImageUrl' in value) || value['coverImageUrl'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('deletedAt' in value) || value['deletedAt'] === undefined) return false;
    if (!('emoji' in value) || value['emoji'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('identifier' in value) || value['identifier'] === undefined) return false;
    if (!('isDeployed' in value) || value['isDeployed'] === undefined) return false;
    if (!('isMember' in value) || value['isMember'] === undefined) return false;
    if (!('memberRole' in value) || value['memberRole'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('sortOrder' in value) || value['sortOrder'] === undefined) return false;
    if (!('totalCycles' in value) || value['totalCycles'] === undefined) return false;
    if (!('totalMembers' in value) || value['totalMembers'] === undefined) return false;
    if (!('totalModules' in value) || value['totalModules'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('updatedBy' in value) || value['updatedBy'] === undefined) return false;
    if (!('workspace' in value) || value['workspace'] === undefined) return false;
    return true;
}

export function ProjectFromJSON(json: any): Project {
    return ProjectFromJSONTyped(json, false);
}

export function ProjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): Project {
    if (json == null) {
        return json;
    }
    return {
        
        'archiveIn': json['archive_in'] == null ? undefined : json['archive_in'],
        'archivedAt': json['archived_at'] == null ? undefined : (new Date(json['archived_at'])),
        'closeIn': json['close_in'] == null ? undefined : json['close_in'],
        'coverImage': json['cover_image'] == null ? undefined : json['cover_image'],
        'coverImageAsset': json['cover_image_asset'] == null ? undefined : json['cover_image_asset'],
        'coverImageUrl': json['cover_image_url'],
        'createdAt': (new Date(json['created_at'])),
        'createdBy': json['created_by'],
        'cycleView': json['cycle_view'] == null ? undefined : json['cycle_view'],
        'defaultAssignee': json['default_assignee'] == null ? undefined : json['default_assignee'],
        'defaultState': json['default_state'] == null ? undefined : json['default_state'],
        'deletedAt': (json['deleted_at'] == null ? null : new Date(json['deleted_at'])),
        'description': json['description'] == null ? undefined : json['description'],
        'descriptionHtml': json['description_html'] == null ? undefined : json['description_html'],
        'descriptionText': json['description_text'] == null ? undefined : json['description_text'],
        'emoji': json['emoji'],
        'estimate': json['estimate'] == null ? undefined : json['estimate'],
        'guestViewAllFeatures': json['guest_view_all_features'] == null ? undefined : json['guest_view_all_features'],
        'iconProp': json['icon_prop'] == null ? undefined : json['icon_prop'],
        'id': json['id'],
        'identifier': json['identifier'],
        'inboxView': json['inbox_view'] == null ? undefined : json['inbox_view'],
        'isDeployed': json['is_deployed'],
        'isIssueTypeEnabled': json['is_issue_type_enabled'] == null ? undefined : json['is_issue_type_enabled'],
        'isMember': json['is_member'],
        'isTimeTrackingEnabled': json['is_time_tracking_enabled'] == null ? undefined : json['is_time_tracking_enabled'],
        'issueViewsView': json['issue_views_view'] == null ? undefined : json['issue_views_view'],
        'logoProps': json['logo_props'] == null ? undefined : json['logo_props'],
        'memberRole': json['member_role'],
        'moduleView': json['module_view'] == null ? undefined : json['module_view'],
        'name': json['name'],
        'network': json['network'] == null ? undefined : NetworkEnumFromJSON(json['network']),
        'pageView': json['page_view'] == null ? undefined : json['page_view'],
        'projectLead': json['project_lead'] == null ? undefined : json['project_lead'],
        'sortOrder': json['sort_order'],
        'timezone': json['timezone'] == null ? undefined : TimezoneEnumFromJSON(json['timezone']),
        'totalCycles': json['total_cycles'],
        'totalMembers': json['total_members'],
        'totalModules': json['total_modules'],
        'updatedAt': (new Date(json['updated_at'])),
        'updatedBy': json['updated_by'],
        'workspace': json['workspace'],
    };
}

export function ProjectToJSON(json: any): Project {
    return ProjectToJSONTyped(json, false);
}

export function ProjectToJSONTyped(value?: Omit<Project, 'cover_image_url'|'created_at'|'created_by'|'deleted_at'|'emoji'|'id'|'is_deployed'|'is_member'|'member_role'|'sort_order'|'total_cycles'|'total_members'|'total_modules'|'updated_at'|'updated_by'|'workspace'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'archive_in': value['archiveIn'],
        'archived_at': value['archivedAt'] == null ? undefined : ((value['archivedAt'] as any).toISOString()),
        'close_in': value['closeIn'],
        'cover_image': value['coverImage'],
        'cover_image_asset': value['coverImageAsset'],
        'cycle_view': value['cycleView'],
        'default_assignee': value['defaultAssignee'],
        'default_state': value['defaultState'],
        'description': value['description'],
        'description_html': value['descriptionHtml'],
        'description_text': value['descriptionText'],
        'estimate': value['estimate'],
        'guest_view_all_features': value['guestViewAllFeatures'],
        'icon_prop': value['iconProp'],
        'identifier': value['identifier'],
        'inbox_view': value['inboxView'],
        'is_issue_type_enabled': value['isIssueTypeEnabled'],
        'is_time_tracking_enabled': value['isTimeTrackingEnabled'],
        'issue_views_view': value['issueViewsView'],
        'logo_props': value['logoProps'],
        'module_view': value['moduleView'],
        'name': value['name'],
        'network': NetworkEnumToJSON(value['network']),
        'page_view': value['pageView'],
        'project_lead': value['projectLead'],
        'timezone': TimezoneEnumToJSON(value['timezone']),
    };
}

