/* tslint:disable */
/* eslint-disable */
/**
 * Plane API
 * API documentation for my specific app
 *
 * The version of the OpenAPI document: 1.0.0 (1.0.0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `backlog` - Backlog
 * * `planned` - Planned
 * * `in-progress` - In Progress
 * * `paused` - Paused
 * * `completed` - Completed
 * * `cancelled` - Cancelled
 * @export
 */
export const StatusA3dEnum = {
    Backlog: 'backlog',
    Planned: 'planned',
    InProgress: 'in-progress',
    Paused: 'paused',
    Completed: 'completed',
    Cancelled: 'cancelled'
} as const;
export type StatusA3dEnum = typeof StatusA3dEnum[keyof typeof StatusA3dEnum];


export function instanceOfStatusA3dEnum(value: any): boolean {
    for (const key in StatusA3dEnum) {
        if (Object.prototype.hasOwnProperty.call(StatusA3dEnum, key)) {
            if (StatusA3dEnum[key as keyof typeof StatusA3dEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function StatusA3dEnumFromJSON(json: any): StatusA3dEnum {
    return StatusA3dEnumFromJSONTyped(json, false);
}

export function StatusA3dEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatusA3dEnum {
    return json as StatusA3dEnum;
}

export function StatusA3dEnumToJSON(value?: StatusA3dEnum | null): any {
    return value as any;
}

export function StatusA3dEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): StatusA3dEnum {
    return value as StatusA3dEnum;
}

