/* tslint:disable */
/* eslint-disable */
/**
 * Plane API
 * API documentation for my specific app
 *
 * The version of the OpenAPI document: 1.0.0 (1.0.0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GroupEnum } from './GroupEnum';
import {
    GroupEnumFromJSON,
    GroupEnumFromJSONTyped,
    GroupEnumToJSON,
    GroupEnumToJSONTyped,
} from './GroupEnum';

/**
 * 
 * @export
 * @interface StateLite
 */
export interface StateLite {
    /**
     * 
     * @type {string}
     * @memberof StateLite
     */
    readonly color: string;
    /**
     * 
     * @type {GroupEnum}
     * @memberof StateLite
     */
    readonly group: GroupEnum;
    /**
     * 
     * @type {string}
     * @memberof StateLite
     */
    readonly id: string;
    /**
     * 
     * @type {string}
     * @memberof StateLite
     */
    readonly name: string;
}



/**
 * Check if a given object implements the StateLite interface.
 */
export function instanceOfStateLite(value: object): value is StateLite {
    if (!('color' in value) || value['color'] === undefined) return false;
    if (!('group' in value) || value['group'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function StateLiteFromJSON(json: any): StateLite {
    return StateLiteFromJSONTyped(json, false);
}

export function StateLiteFromJSONTyped(json: any, ignoreDiscriminator: boolean): StateLite {
    if (json == null) {
        return json;
    }
    return {
        
        'color': json['color'],
        'group': GroupEnumFromJSON(json['group']),
        'id': json['id'],
        'name': json['name'],
    };
}

export function StateLiteToJSON(json: any): StateLite {
    return StateLiteToJSONTyped(json, false);
}

export function StateLiteToJSONTyped(value?: Omit<StateLite, 'color'|'group'|'id'|'name'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

