/* tslint:disable */
/* eslint-disable */
/**
 * Plane API
 * API documentation for my specific app
 *
 * The version of the OpenAPI document: 1.0.0 (1.0.0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserLite
 */
export interface UserLite {
    /**
     * 
     * @type {string}
     * @memberof UserLite
     */
    readonly avatar: string;
    /**
     * 
     * @type {string}
     * @memberof UserLite
     */
    readonly avatarUrl: string;
    /**
     * 
     * @type {string}
     * @memberof UserLite
     */
    readonly displayName: string;
    /**
     * 
     * @type {string}
     * @memberof UserLite
     */
    readonly email: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserLite
     */
    readonly firstName: string;
    /**
     * 
     * @type {string}
     * @memberof UserLite
     */
    readonly id: string;
    /**
     * 
     * @type {string}
     * @memberof UserLite
     */
    readonly lastName: string;
}

/**
 * Check if a given object implements the UserLite interface.
 */
export function instanceOfUserLite(value: object): value is UserLite {
    if (!('avatar' in value) || value['avatar'] === undefined) return false;
    if (!('avatarUrl' in value) || value['avatarUrl'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    return true;
}

export function UserLiteFromJSON(json: any): UserLite {
    return UserLiteFromJSONTyped(json, false);
}

export function UserLiteFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserLite {
    if (json == null) {
        return json;
    }
    return {
        
        'avatar': json['avatar'],
        'avatarUrl': json['avatar_url'],
        'displayName': json['display_name'],
        'email': json['email'],
        'firstName': json['first_name'],
        'id': json['id'],
        'lastName': json['last_name'],
    };
}

export function UserLiteToJSON(json: any): UserLite {
    return UserLiteToJSONTyped(json, false);
}

export function UserLiteToJSONTyped(value?: Omit<UserLite, 'avatar'|'avatar_url'|'display_name'|'email'|'first_name'|'id'|'last_name'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

